# Generated by Django 3.2.15 on 2023-07-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='url',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
