# Generated by Django 3.2.15 on 2023-07-02 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_budget_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.project'),
        ),
    ]
