# Generated by Django 3.2.15 on 2023-07-02 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20230702_2000'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Budget',
        ),
    ]
