"""
Models for Budgets1 App
"""
from django.db import models
from django.contrib.auth.models import User


class Budget1(models.Model):
    """
    Budget1 model
    """
    project = models.CharField(max_length=25, blank=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    above_the_line_total = models.CharField(max_length=25, blank=True)
    below_the_lineB_total = models.CharField(max_length=25, blank=True)
    below_the_lineB_costs_total = models.CharField(max_length=25, blank=True)
    b_labour_and_costs_total = models.CharField(max_length=25, blank=True)
    post_productionC_total = models.CharField(max_length=25, blank=True)
    belowB_andC_total = models.CharField(max_length=25, blank=True)
    above_belowABC_total = models.CharField(max_length=25, blank=True)
    otherD_total = models.CharField(max_length=25, blank=True)
    above_belowABCandD_total = models.CharField(max_length=25, blank=True)
    grand_total = models.CharField(max_length=25, blank=True)
    title = models.CharField(max_length=25, blank=True)
    series = models.CharField(max_length=25, blank=True)
    prodco = models.CharField(max_length=25, blank=True)
    format = models.CharField(max_length=25, blank=True)
    location = models.CharField(max_length=25, blank=True)
    dated = models.CharField(max_length=25, blank=True)
    writer = models.CharField(max_length=25, blank=True)
    prelimfin = models.CharField(max_length=25, blank=True)
    preparedby = models.CharField(max_length=25, blank=True)
    approvedby = models.CharField(max_length=25, blank=True)
    approvedbyco = models.CharField(max_length=25, blank=True)
    research = models.CharField(max_length=25, blank=True)
    prep = models.CharField(max_length=25, blank=True)
    shoot = models.CharField(max_length=25, blank=True)
    wrap = models.CharField(max_length=25, blank=True)
    post = models.CharField(max_length=25, blank=True)
    length_total = models.CharField(max_length=25, blank=True)
    story_rights = models.CharField(max_length=25, blank=True)
    miscellaneous = models.CharField(max_length=25, blank=True)
    rights_total = models.CharField(max_length=25, blank=True)
    research_development = models.CharField(max_length=25, blank=True)
    prelim_budget = models.CharField(max_length=25, blank=True)
    consultant_expenses = models.CharField(max_length=25, blank=True)
    office_expenses = models.CharField(max_length=25, blank=True)
    staff = models.CharField(max_length=25, blank=True)
    travel_expenses_development = models.CharField(max_length=25, blank=True)
    living_expenses_development = models.CharField(max_length=25, blank=True)
    other_development = models.CharField(max_length=25, blank=True)
    fringes_taxes_development = models.CharField(max_length=25, blank=True)
    development_total = models.CharField(max_length=25, blank=True)
    writers_quantity = models.CharField(max_length=25, blank=True)
    writers_units_number = models.CharField(max_length=25, blank=True)
    writers_units_name = models.CharField(max_length=25, blank=True)
    writers_rate = models.CharField(max_length=25, blank=True)
    writers_total = models.CharField(max_length=25, blank=True)
    consultants_quantity = models.CharField(max_length=25, blank=True)
    consultants_units_number = models.CharField(max_length=25, blank=True)
    consultants_units_name = models.CharField(max_length=25, blank=True)
    consultants_rate = models.CharField(max_length=25, blank=True)
    consultants_total = models.CharField(max_length=25, blank=True)
    editors_scenario_quantity = models.CharField(max_length=25, blank=True)
    editors_scenario_units_number = models.CharField(max_length=25, blank=True)
    editors_scenario_units_name = models.CharField(max_length=25, blank=True)
    editors_scenario_rate = models.CharField(max_length=25, blank=True)
    editors_scenario_total = models.CharField(max_length=25, blank=True)
    admin_scenario_quantity = models.CharField(max_length=25, blank=True)
    admin_scenario_units_number = models.CharField(max_length=25, blank=True)
    admin_scenario_units_name = models.CharField(max_length=25, blank=True)
    admin_scenario_rate = models.CharField(max_length=25, blank=True)
    admin_scenario_total = models.CharField(max_length=25, blank=True)
    office_expenses_scenario = models.CharField(max_length=25, blank=True)
    travel_expenses_scenario = models.CharField(max_length=25, blank=True)
    living_expenses_scenario = models.CharField(max_length=25, blank=True)
    other_scenario = models.CharField(max_length=25, blank=True)
    fringes_taxes_scenario = models.CharField(max_length=25, blank=True)
    scenario_total = models.CharField(max_length=25, blank=True)
    executive_producers_quantity = models.CharField(max_length=25, blank=True)
    producers_quantity = models.CharField(max_length=25, blank=True)
    line_producers_quantity = models.CharField(max_length=25, blank=True)
    co_producers_quantity = models.CharField(max_length=25, blank=True)
    associate_producers_quantity = models.CharField(max_length=25, blank=True)
    directors_quantity = models.CharField(max_length=25, blank=True)
    unit2_directors_quantity = models.CharField(max_length=25, blank=True)
    executive_producers_rate = models.CharField(max_length=25, blank=True)
    producers_rate = models.CharField(max_length=25, blank=True)
    line_producers_rate = models.CharField(max_length=25, blank=True)
    co_producers_rate = models.CharField(max_length=25, blank=True)
    associate_producers_rate = models.CharField(max_length=25, blank=True)
    directors_rate = models.CharField(max_length=25, blank=True)
    unit2_directors_rate = models.CharField(max_length=25, blank=True)
    executive_producers_total = models.CharField(max_length=25, blank=True)
    producers_total = models.CharField(max_length=25, blank=True)
    line_producers_total = models.CharField(max_length=25, blank=True)
    co_producers_total = models.CharField(max_length=25, blank=True)
    associate_producers_total = models.CharField(max_length=25, blank=True)
    directors_total = models.CharField(max_length=25, blank=True)
    unit2_directors_total = models.CharField(max_length=25, blank=True)
    travel_expenses_producers_dirs = models.CharField(
        max_length=25, blank=True)
    living_expenses_producers_dirs = models.CharField(
        max_length=25, blank=True)
    other_producers_dirs = models.CharField(max_length=25, blank=True)
    fringes_taxes_producers_dirs = models.CharField(max_length=25, blank=True)
    producers_dirs_total = models.CharField(max_length=25, blank=True)
    stars = models.CharField(max_length=25, blank=True)
    stars_rights_payments = models.CharField(max_length=25, blank=True)
    travel_expenses_stars = models.CharField(max_length=25, blank=True)
    living_expenses_stars = models.CharField(max_length=25, blank=True)
    other_stars = models.CharField(max_length=25, blank=True)
    fringes_taxes_stars = models.CharField(max_length=25, blank=True)
    music = models.CharField(max_length=25, blank=True)
    music_supervisor = models.CharField(max_length=25, blank=True)
    travel_expenses_music = models.CharField(max_length=25, blank=True)
    living_expenses_music = models.CharField(max_length=25, blank=True)
    music_rights_addl_songs = models.CharField(max_length=25, blank=True)
    other_music = models.CharField(max_length=25, blank=True)
    fringes_taxes_music = models.CharField(max_length=25, blank=True)
    stars_music_total = models.CharField(max_length=25, blank=True)
    principals_quantity = models.CharField(max_length=25, blank=True)
    principals_units_number = models.CharField(max_length=25, blank=True)
    principals_units_name = models.CharField(max_length=25, blank=True)
    principals_rate = models.CharField(max_length=25, blank=True)
    actors_quantity = models.CharField(max_length=25, blank=True)
    actors_units_number = models.CharField(max_length=25, blank=True)
    actors_units_name = models.CharField(max_length=25, blank=True)
    actors_rate = models.CharField(max_length=25, blank=True)
    stuntcoordinators_quantity = models.CharField(max_length=25, blank=True)
    stuntcoordinators_units_number = models.CharField(
        max_length=25, blank=True)
    stuntcoordinators_units_name = models.CharField(max_length=25, blank=True)
    stuntcoordinators_rate = models.CharField(max_length=25, blank=True)
    stuntperformers_quantity = models.CharField(max_length=25, blank=True)
    stuntperformers_units_number = models.CharField(max_length=25, blank=True)
    stuntperformers_units_name = models.CharField(max_length=25, blank=True)
    stuntperformers_rate = models.CharField(max_length=25, blank=True)
    otherperformers_quantity = models.CharField(max_length=25, blank=True)
    otherperformers_units_number = models.CharField(max_length=25, blank=True)
    otherperformers_units_name = models.CharField(max_length=25, blank=True)
    otherperformers_rate = models.CharField(max_length=25, blank=True)
    extras_quantity = models.CharField(max_length=25, blank=True)
    extras_units_number = models.CharField(max_length=25, blank=True)
    extras_units_name = models.CharField(max_length=25, blank=True)
    extras_rate = models.CharField(max_length=25, blank=True)
    principals_total = models.CharField(max_length=25, blank=True)
    actors_total = models.CharField(max_length=25, blank=True)
    stuntcoordinators_total = models.CharField(max_length=25, blank=True)
    stuntperformers_total = models.CharField(max_length=25, blank=True)
    otherperformers_total = models.CharField(max_length=25, blank=True)
    extras_total = models.CharField(max_length=25, blank=True)
    casting_director = models.CharField(max_length=25, blank=True)
    extras_casting = models.CharField(max_length=25, blank=True)
    prin_2_qty = models.CharField(max_length=25, blank=True)
    prin_2_uno = models.CharField(max_length=25, blank=True)
    prin_2_una = models.CharField(max_length=25, blank=True)
    prin_2_rt = models.CharField(max_length=25, blank=True)
    prin_3_qty = models.CharField(max_length=25, blank=True)
    prin_3_uno = models.CharField(max_length=25, blank=True)
    prin_3_una = models.CharField(max_length=25, blank=True)
    prin_3_rt = models.CharField(max_length=25, blank=True)
    actors_2_qty = models.CharField(max_length=25, blank=True)
    actors_2_uno = models.CharField(max_length=25, blank=True)
    actors_2_una = models.CharField(max_length=25, blank=True)
    actors_2_rt = models.CharField(max_length=25, blank=True)
    actors_3_qty = models.CharField(max_length=25, blank=True)
    actors_3_uno = models.CharField(max_length=25, blank=True)
    actors_3_una = models.CharField(max_length=25, blank=True)
    actors_3_rt = models.CharField(max_length=25, blank=True)
    actors_4_qty = models.CharField(max_length=25, blank=True)
    actors_4_uno = models.CharField(max_length=25, blank=True)
    actors_4_una = models.CharField(max_length=25, blank=True)
    actors_4_rt = models.CharField(max_length=25, blank=True)
    actors_5_qty = models.CharField(max_length=25, blank=True)
    actors_5_uno = models.CharField(max_length=25, blank=True)
    actors_5_una = models.CharField(max_length=25, blank=True)
    actors_5_rt = models.CharField(max_length=25, blank=True)
    actors_6_qty = models.CharField(max_length=25, blank=True)
    actors_6_uno = models.CharField(max_length=25, blank=True)
    actors_6_una = models.CharField(max_length=25, blank=True)
    actors_6_rt = models.CharField(max_length=25, blank=True)
    actors_7_qty = models.CharField(max_length=25, blank=True)
    actors_7_uno = models.CharField(max_length=25, blank=True)
    actors_7_una = models.CharField(max_length=25, blank=True)
    actors_7_rt = models.CharField(max_length=25, blank=True)
    actors_week_qty = models.CharField(max_length=25, blank=True)
    actors_week_uno = models.CharField(max_length=25, blank=True)
    actors_week_una = models.CharField(max_length=25, blank=True)
    actors_week_rt = models.CharField(max_length=25, blank=True)
    actors_day_qty = models.CharField(max_length=25, blank=True)
    actors_day_uno = models.CharField(max_length=25, blank=True)
    actors_day_una = models.CharField(max_length=25, blank=True)
    actors_day_rt = models.CharField(max_length=25, blank=True)
    princ2_total = models.CharField(max_length=25, blank=True)
    princ3_total = models.CharField(max_length=25, blank=True)
    actor2_total = models.CharField(max_length=25, blank=True)
    actor3_total = models.CharField(max_length=25, blank=True)
    actor4_total = models.CharField(max_length=25, blank=True)
    actor5_total = models.CharField(max_length=25, blank=True)
    actor6_total = models.CharField(max_length=25, blank=True)
    actor7_total = models.CharField(max_length=25, blank=True)
    actorweek_total = models.CharField(max_length=25, blank=True)
    actorday_total = models.CharField(max_length=25, blank=True)
    other_cast = models.CharField(max_length=25, blank=True)
    holidays_cast = models.CharField(max_length=25, blank=True)
    overtime_cast = models.CharField(max_length=25, blank=True)
    days6th7th_cast = models.CharField(max_length=25, blank=True)
    rehersals_cast = models.CharField(max_length=25, blank=True)
    holidays_unit_cast = models.CharField(max_length=25, blank=True)
    overtime_unit_cast = models.CharField(max_length=25, blank=True)
    days6th7th_unit_cast = models.CharField(max_length=25, blank=True)
    rehersals_unit_cast = models.CharField(max_length=25, blank=True)
    fringes_taxes_cast = models.CharField(max_length=25, blank=True)
    rights_payments_cast = models.CharField(max_length=25, blank=True)
    cast_total = models.CharField(max_length=25, blank=True)
    fringes_taxes_production = models.CharField(max_length=25, blank=True)
    production_manager_quantity = models.CharField(max_length=25, blank=True)
    production_manager_units_number = models.CharField(
        max_length=25, blank=True)
    production_manager_units_name = models.CharField(max_length=25, blank=True)
    production_manager_rate = models.CharField(max_length=25, blank=True)
    production_supervisor_quantity = models.CharField(
        max_length=25, blank=True)
    production_supervisor_units_number = models.CharField(
        max_length=25, blank=True)
    production_supervisor_units_name = models.CharField(
        max_length=25, blank=True)
    production_supervisor_rate = models.CharField(max_length=25, blank=True)
    production_coordinator_quantity = models.CharField(
        max_length=25, blank=True)
    production_coordinator_units_number = models.CharField(
        max_length=25, blank=True)
    production_coordinator_units_name = models.CharField(
        max_length=25, blank=True)
    production_coordinator_rate = models.CharField(max_length=25, blank=True)
    unit_manager_quantity = models.CharField(max_length=25, blank=True)
    unit_manager_units_number = models.CharField(max_length=25, blank=True)
    unit_manager_units_name = models.CharField(max_length=25, blank=True)
    unit_manager_rate = models.CharField(max_length=25, blank=True)
    location_manager_quantity = models.CharField(max_length=25, blank=True)
    location_manager_units_number = models.CharField(max_length=25, blank=True)
    location_manager_units_name = models.CharField(max_length=25, blank=True)
    location_manager_rate = models.CharField(max_length=25, blank=True)
    location_manager_assistant_quantity = models.CharField(
        max_length=25, blank=True)
    location_manager_assistant_units_number = models.CharField(
        max_length=25, blank=True)
    location_manager_assistant_units_name = models.CharField(
        max_length=25, blank=True)
    location_manager_assistant_rate = models.CharField(
        max_length=25, blank=True)
    production_assistants_quantity = models.CharField(
        max_length=25, blank=True)
    production_assistants_units_number = models.CharField(
        max_length=25, blank=True)
    production_assistants_units_name = models.CharField(
        max_length=25, blank=True)
    production_assistants_rate = models.CharField(max_length=25, blank=True)
    production_secretary_quantity = models.CharField(max_length=25, blank=True)
    production_secretary_units_number = models.CharField(
        max_length=25, blank=True)
    production_secretary_units_name = models.CharField(
        max_length=25, blank=True)
    production_secretary_rate = models.CharField(max_length=25, blank=True)
    production_accountant_quantity = models.CharField(
        max_length=25, blank=True)
    production_accountant_units_number = models.CharField(
        max_length=25, blank=True)
    production_accountant_units_name = models.CharField(
        max_length=25, blank=True)
    production_accountant_rate = models.CharField(max_length=25, blank=True)
    production_accountant_assistant_quantity = models.CharField(
        max_length=25, blank=True)
    production_accountant_assistant_units_number = models.CharField(
        max_length=25, blank=True)
    production_accountant_assistant_units_name = models.CharField(
        max_length=25, blank=True)
    production_accountant_assistant_rate = models.CharField(
        max_length=25, blank=True)
    scriptsupervisor_continuity_quantity = models.CharField(
        max_length=25, blank=True)
    scriptsupervisor_continuity_units_number = models.CharField(
        max_length=25, blank=True)
    scriptsupervisor_continuity_units_name = models.CharField(
        max_length=25, blank=True)
    scriptsupervisor_continuity_rate = models.CharField(
        max_length=25, blank=True)
    payroll_quantity = models.CharField(max_length=25, blank=True)
    payroll_units_number = models.CharField(max_length=25, blank=True)
    payroll_units_name = models.CharField(max_length=25, blank=True)
    payroll_rate = models.CharField(max_length=25, blank=True)
    other_production_quantity = models.CharField(max_length=25, blank=True)
    other_production_units_number = models.CharField(max_length=25, blank=True)
    other_production_units_name = models.CharField(max_length=25, blank=True)
    other_production_rate = models.CharField(max_length=25, blank=True)
    directors_assistant_quantity = models.CharField(max_length=25, blank=True)
    directors_assistant_units_number = models.CharField(
        max_length=25, blank=True)
    directors_assistant_units_name = models.CharField(
        max_length=25, blank=True)
    directors_assistant_rate = models.CharField(max_length=25, blank=True)
    assistant_director_1st_quantity = models.CharField(
        max_length=25, blank=True)
    assistant_director_1st_units_number = models.CharField(
        max_length=25, blank=True)
    assistant_director_1st_units_name = models.CharField(
        max_length=25, blank=True)
    assistant_director_1st_rate = models.CharField(max_length=25, blank=True)
    assistant_director_2nd_quantity = models.CharField(
        max_length=25, blank=True)
    assistant_director_2nd_units_number = models.CharField(
        max_length=25, blank=True)
    assistant_director_2nd_units_name = models.CharField(
        max_length=25, blank=True)
    assistant_director_2nd_rate = models.CharField(max_length=25, blank=True)
    assistant_director_3rd_quantity = models.CharField(
        max_length=25, blank=True)
    assistant_director_3rd_units_number = models.CharField(
        max_length=25, blank=True)
    assistant_director_3rd_units_name = models.CharField(
        max_length=25, blank=True)
    assistant_director_3rd_rate = models.CharField(max_length=25, blank=True)
    craft_services_quantity = models.CharField(max_length=25, blank=True)
    craft_services_units_number = models.CharField(max_length=25, blank=True)
    craft_services_units_name = models.CharField(max_length=25, blank=True)
    craft_services_rate = models.CharField(max_length=25, blank=True)
    productionmanager_total = models.CharField(max_length=25, blank=True)
    productionsupervisor_total = models.CharField(max_length=25, blank=True)
    productioncoordinator_total = models.CharField(max_length=25, blank=True)
    unitmanager_total = models.CharField(max_length=25, blank=True)
    locationmanager_total = models.CharField(max_length=25, blank=True)
    locationmanagerassistant_total = models.CharField(
        max_length=25, blank=True)
    productionassistants_total = models.CharField(max_length=25, blank=True)
    productionsecretary_total = models.CharField(max_length=25, blank=True)
    productionaccountant_total = models.CharField(max_length=25, blank=True)
    productionaccountantassistant_total = models.CharField(
        max_length=25, blank=True)
    scriptsupervisorcontinuity_total = models.CharField(
        max_length=25, blank=True)
    payroll_total = models.CharField(max_length=25, blank=True)
    otherproduction_total = models.CharField(max_length=25, blank=True)
    directorsassistant_total = models.CharField(max_length=25, blank=True)
    assistantdirector1st_total = models.CharField(max_length=25, blank=True)
    assistantdirector2nd_total = models.CharField(max_length=25, blank=True)
    assistantdirector3rd_total = models.CharField(max_length=25, blank=True)
    craftservices_total = models.CharField(max_length=25, blank=True)
    productionstaff_total = models.CharField(max_length=25, blank=True)
    production_designer_quantity = models.CharField(max_length=25, blank=True)
    holidays_pro_sta = models.CharField(max_length=25, blank=True)
    overtime_pro_sta = models.CharField(max_length=25, blank=True)
    days6th7th_pro_sta = models.CharField(max_length=25, blank=True)
    other_pro_sta = models.CharField(max_length=25, blank=True)
    box_rent_pro_sta = models.CharField(max_length=25, blank=True)
    holidays_unit_pro_sta = models.CharField(max_length=25, blank=True)
    overtime_unit_pro_sta = models.CharField(max_length=25, blank=True)
    days6th7th_unit_pro_sta = models.CharField(max_length=25, blank=True)
    other_unit_pro_sta = models.CharField(max_length=25, blank=True)
    box_rent_unit_pro_sta = models.CharField(max_length=25, blank=True)
    production_manager_qty_prep = models.CharField(max_length=25, blank=True)
    production_manager_uno_prep = models.CharField(max_length=25, blank=True)
    production_manager_una_prep = models.CharField(max_length=25, blank=True)
    production_manager_rt_prep = models.CharField(max_length=25, blank=True)
    production_manager_qty_wrap = models.CharField(max_length=25, blank=True)
    production_manager_uno_wrap = models.CharField(max_length=25, blank=True)
    production_manager_una_wrap = models.CharField(max_length=25, blank=True)
    production_manager_rt_wrap = models.CharField(max_length=25, blank=True)
    production_supervisor_qty_prep = models.CharField(
        max_length=25, blank=True)
    production_supervisor_uno_prep = models.CharField(
        max_length=25, blank=True)
    production_supervisor_una_prep = models.CharField(
        max_length=25, blank=True)
    production_supervisor_rt_prep = models.CharField(
        max_length=25, blank=True)
    production_supervisor_qty_wrap = models.CharField(
        max_length=25, blank=True)
    production_supervisor_uno_wrap = models.CharField(
        max_length=25, blank=True)
    production_supervisor_una_wrap = models.CharField(
        max_length=25, blank=True)
    production_supervisor_rt_wrap = models.CharField(
        max_length=25, blank=True)
    production_coordinator_qty_prep = models.CharField(
        max_length=25, blank=True)
    production_coordinator_uno_prep = models.CharField(
        max_length=25, blank=True)
    production_coordinator_una_prep = models.CharField(
        max_length=25, blank=True)
    production_coordinator_rt_prep = models.CharField(
        max_length=25, blank=True)
    production_coordinator_qty_wrap = models.CharField(
        max_length=25, blank=True)
    production_coordinator_uno_wrap = models.CharField(
        max_length=25, blank=True)
    production_coordinator_una_wrap = models.CharField(
        max_length=25, blank=True)
    production_coordinator_rt_wrap = models.CharField(
        max_length=25, blank=True)
    unit_manager_qty_prep = models.CharField(max_length=25, blank=True)
    unit_manager_uno_prep = models.CharField(max_length=25, blank=True)
    unit_manager_una_prep = models.CharField(max_length=25, blank=True)
    unit_manager_rt_prep = models.CharField(max_length=25, blank=True)
    unit_manager_qty_wrap = models.CharField(max_length=25, blank=True)
    unit_manager_uno_wrap = models.CharField(max_length=25, blank=True)
    unit_manager_una_wrap = models.CharField(max_length=25, blank=True)
    unit_manager_rt_wrap = models.CharField(max_length=25, blank=True)
    location_manager_qty_prep = models.CharField(max_length=25, blank=True)
    location_manager_uno_prep = models.CharField(max_length=25, blank=True)
    location_manager_una_prep = models.CharField(max_length=25, blank=True)
    location_manager_rt_prep = models.CharField(max_length=25, blank=True)
    location_manager_qty_wrap = models.CharField(max_length=25, blank=True)
    location_manager_uno_wrap = models.CharField(max_length=25, blank=True)
    location_manager_una_wrap = models.CharField(max_length=25, blank=True)
    location_manager_rt_wrap = models.CharField(max_length=25, blank=True)
    location_manager_ass_qty_prep = models.CharField(max_length=25, blank=True)
    location_manager_ass_uno_prep = models.CharField(max_length=25, blank=True)
    location_manager_ass_una_prep = models.CharField(max_length=25, blank=True)
    location_manager_ass_rt_prep = models.CharField(max_length=25, blank=True)
    location_manager_ass_qty_wrap = models.CharField(max_length=25, blank=True)
    location_manager_ass_uno_wrap = models.CharField(max_length=25, blank=True)
    location_manager_ass_una_wrap = models.CharField(max_length=25, blank=True)
    location_manager_ass_rt_wrap = models.CharField(max_length=25, blank=True)
    production_ass_qty_prep = models.CharField(max_length=25, blank=True)
    production_ass_uno_prep = models.CharField(max_length=25, blank=True)
    production_ass_una_prep = models.CharField(max_length=25, blank=True)
    production_ass_rt_prep = models.CharField(max_length=25, blank=True)
    production_ass_qty_wrap = models.CharField(max_length=25, blank=True)
    production_ass_uno_wrap = models.CharField(max_length=25, blank=True)
    production_ass_una_wrap = models.CharField(max_length=25, blank=True)
    production_ass_rt_wrap = models.CharField(max_length=25, blank=True)
    production_sec_qty_prep = models.CharField(max_length=25, blank=True)
    production_sec_uno_prep = models.CharField(max_length=25, blank=True)
    production_sec_una_prep = models.CharField(max_length=25, blank=True)
    production_sec_rt_prep = models.CharField(max_length=25, blank=True)
    production_sec_qty_wrap = models.CharField(max_length=25, blank=True)
    production_sec_uno_wrap = models.CharField(max_length=25, blank=True)
    production_sec_una_wrap = models.CharField(max_length=25, blank=True)
    production_sec_rt_wrap = models.CharField(max_length=25, blank=True)
    production_acc_qty_prep = models.CharField(max_length=25, blank=True)
    production_acc_uno_prep = models.CharField(max_length=25, blank=True)
    production_acc_una_prep = models.CharField(max_length=25, blank=True)
    production_acc_rt_prep = models.CharField(max_length=25, blank=True)
    production_acc_qty_wrap = models.CharField(max_length=25, blank=True)
    production_acc_uno_wrap = models.CharField(max_length=25, blank=True)
    production_acc_una_wrap = models.CharField(max_length=25, blank=True)
    production_acc_rt_wrap = models.CharField(max_length=25, blank=True)
    production_acc_ass_qty_prep = models.CharField(max_length=25, blank=True)
    production_acc_ass_uno_prep = models.CharField(max_length=25, blank=True)
    production_acc_ass_una_prep = models.CharField(max_length=25, blank=True)
    production_acc_ass_rt_prep = models.CharField(max_length=25, blank=True)
    production_acc_ass_qty_wrap = models.CharField(max_length=25, blank=True)
    production_acc_ass_uno_wrap = models.CharField(max_length=25, blank=True)
    production_acc_ass_una_wrap = models.CharField(max_length=25, blank=True)
    production_acc_ass_rt_wrap = models.CharField(max_length=25, blank=True)
    scriptsupervisor_con_qty_prep = models.CharField(max_length=25, blank=True)
    scriptsupervisor_con_uno_prep = models.CharField(max_length=25, blank=True)
    scriptsupervisor_con_una_prep = models.CharField(max_length=25, blank=True)
    scriptsupervisor_con_rt_prep = models.CharField(max_length=25, blank=True)
    scriptsupervisor_con_qty_wrap = models.CharField(max_length=25, blank=True)
    scriptsupervisor_con_uno_wrap = models.CharField(max_length=25, blank=True)
    scriptsupervisor_con_una_wrap = models.CharField(max_length=25, blank=True)
    scriptsupervisor_con_rt_wrap = models.CharField(max_length=25, blank=True)
    payroll_qty_prep = models.CharField(max_length=25, blank=True)
    payroll_uno_prep = models.CharField(max_length=25, blank=True)
    payroll_una_prep = models.CharField(max_length=25, blank=True)
    payroll_rt_prep = models.CharField(max_length=25, blank=True)
    payroll_qty_wrap = models.CharField(max_length=25, blank=True)
    payroll_uno_wrap = models.CharField(max_length=25, blank=True)
    payroll_una_wrap = models.CharField(max_length=25, blank=True)
    payroll_rt_wrap = models.CharField(max_length=25, blank=True)
    other_pro_qty_prep = models.CharField(max_length=25, blank=True)
    other_pro_uno_prep = models.CharField(max_length=25, blank=True)
    other_pro_una_prep = models.CharField(max_length=25, blank=True)
    other_pro_rt_prep = models.CharField(max_length=25, blank=True)
    other_pro_qty_wrap = models.CharField(max_length=25, blank=True)
    other_pro_uno_wrap = models.CharField(max_length=25, blank=True)
    other_pro_una_wrap = models.CharField(max_length=25, blank=True)
    other_pro_rt_wrap = models.CharField(max_length=25, blank=True)
    directors_ass_qty_prep = models.CharField(max_length=25, blank=True)
    directors_ass_uno_prep = models.CharField(max_length=25, blank=True)
    directors_ass_una_prep = models.CharField(max_length=25, blank=True)
    directors_ass_rt_prep = models.CharField(max_length=25, blank=True)
    directors_ass_qty_wrap = models.CharField(max_length=25, blank=True)
    directors_ass_uno_wrap = models.CharField(max_length=25, blank=True)
    directors_ass_una_wrap = models.CharField(max_length=25, blank=True)
    directors_ass_rt_wrap = models.CharField(max_length=25, blank=True)
    ass_director_1st_qty_prep = models.CharField(max_length=25, blank=True)
    ass_director_1st_uno_prep = models.CharField(max_length=25, blank=True)
    ass_director_1st_una_prep = models.CharField(max_length=25, blank=True)
    ass_director_1st_rt_prep = models.CharField(max_length=25, blank=True)
    ass_director_1st_qty_wrap = models.CharField(max_length=25, blank=True)
    ass_director_1st_uno_wrap = models.CharField(max_length=25, blank=True)
    ass_director_1st_una_wrap = models.CharField(max_length=25, blank=True)
    ass_director_1st_rt_wrap = models.CharField(max_length=25, blank=True)
    ass_director_2nd_qty_prep = models.CharField(max_length=25, blank=True)
    ass_director_2nd_uno_prep = models.CharField(max_length=25, blank=True)
    ass_director_2nd_una_prep = models.CharField(max_length=25, blank=True)
    ass_director_2nd_rt_prep = models.CharField(max_length=25, blank=True)
    ass_director_2nd_qty_wrap = models.CharField(max_length=25, blank=True)
    ass_director_2nd_uno_wrap = models.CharField(max_length=25, blank=True)
    ass_director_2nd_una_wrap = models.CharField(max_length=25, blank=True)
    ass_director_2nd_rt_wrap = models.CharField(max_length=25, blank=True)
    ass_director_3rd_qty_prep = models.CharField(max_length=25, blank=True)
    ass_director_3rd_uno_prep = models.CharField(max_length=25, blank=True)
    ass_director_3rd_una_prep = models.CharField(max_length=25, blank=True)
    ass_director_3rd_rt_prep = models.CharField(max_length=25, blank=True)
    ass_director_3rd_qty_wrap = models.CharField(max_length=25, blank=True)
    ass_director_3rd_uno_wrap = models.CharField(max_length=25, blank=True)
    ass_director_3rd_una_wrap = models.CharField(max_length=25, blank=True)
    ass_director_3rd_rt_wrap = models.CharField(max_length=25, blank=True)
    craft_services_qty_prep = models.CharField(max_length=25, blank=True)
    craft_services_uno_prep = models.CharField(max_length=25, blank=True)
    craft_services_una_prep = models.CharField(max_length=25, blank=True)
    craft_services_rt_prep = models.CharField(max_length=25, blank=True)
    craft_services_qty_wrap = models.CharField(max_length=25, blank=True)
    craft_services_uno_wrap = models.CharField(max_length=25, blank=True)
    craft_services_una_wrap = models.CharField(max_length=25, blank=True)
    craft_services_rt_wrap = models.CharField(max_length=25, blank=True)
    productionmanagerprep_total = models.CharField(max_length=25, blank=True)
    productionmanagerwrap_total = models.CharField(max_length=25, blank=True)
    productionmanagerall_total = models.CharField(max_length=25, blank=True)
    productionsupervisorprep_total = models.CharField(
        max_length=25, blank=True)
    productionsupervisorwrap_total = models.CharField(
        max_length=25, blank=True)
    productionsupervisorall_total = models.CharField(
        max_length=25, blank=True)
    productioncoordinatorprep_total = models.CharField(
        max_length=25, blank=True)
    productioncoordinatorwrap_total = models.CharField(
        max_length=25, blank=True)
    productioncoordinatorall_total = models.CharField(
        max_length=25, blank=True)
    unitmanagerprep_total = models.CharField(max_length=25, blank=True)
    unitmanagerwrap_total = models.CharField(max_length=25, blank=True)
    unitmanagerall_total = models.CharField(max_length=25, blank=True)
    locationmanagerwrap_total = models.CharField(max_length=25, blank=True)
    locationmanagerprep_total = models.CharField(max_length=25, blank=True)
    locationmanagerall_total = models.CharField(max_length=25, blank=True)
    locmanassprep_total = models.CharField(max_length=25, blank=True)
    locmanasswrap_total = models.CharField(max_length=25, blank=True)
    locmanassall_total = models.CharField(max_length=25, blank=True)
    proassprep_total = models.CharField(max_length=25, blank=True)
    proasswrap_total = models.CharField(max_length=25, blank=True)
    proassall_total = models.CharField(max_length=25, blank=True)
    prosecprep_total = models.CharField(max_length=25, blank=True)
    prosecwrap_total = models.CharField(max_length=25, blank=True)
    prosecall_total = models.CharField(max_length=25, blank=True)
    proaccprep_total = models.CharField(max_length=25, blank=True)
    proaccwrap_total = models.CharField(max_length=25, blank=True)
    proaccall_total = models.CharField(max_length=25, blank=True)
    proaccassprep_total = models.CharField(max_length=25, blank=True)
    proaccasswrap_total = models.CharField(max_length=25, blank=True)
    proaccassall_total = models.CharField(max_length=25, blank=True)
    scriptsupconprep_total = models.CharField(max_length=25, blank=True)
    scriptsupconwrap_total = models.CharField(max_length=25, blank=True)
    scriptsupconall_total = models.CharField(max_length=25, blank=True)
    payrollprep_total = models.CharField(max_length=25, blank=True)
    payrollwrap_total = models.CharField(max_length=25, blank=True)
    payrollall_total = models.CharField(max_length=25, blank=True)
    otherproprep_total = models.CharField(max_length=25, blank=True)
    otherprowrap_total = models.CharField(max_length=25, blank=True)
    otherproall_total = models.CharField(max_length=25, blank=True)
    directorsassprep_total = models.CharField(max_length=25, blank=True)
    directorsasswrap_total = models.CharField(max_length=25, blank=True)
    directorsassall_total = models.CharField(max_length=25, blank=True)
    assdirector1stprep_total = models.CharField(max_length=25, blank=True)
    assdirector1stwrap_total = models.CharField(max_length=25, blank=True)
    assdirector1stall_total = models.CharField(max_length=25, blank=True)
    assdirector2ndprep_total = models.CharField(max_length=25, blank=True)
    assdirector2ndwrap_total = models.CharField(max_length=25, blank=True)
    assdirector2ndall_total = models.CharField(max_length=25, blank=True)
    assdirector3rdprep_total = models.CharField(max_length=25, blank=True)
    assdirector3rdwrap_total = models.CharField(max_length=25, blank=True)
    assdirector3rdall_total = models.CharField(max_length=25, blank=True)
    craftservicesprep_total = models.CharField(max_length=25, blank=True)
    craftserviceswrap_total = models.CharField(max_length=25, blank=True)
    craftservicesall_total = models.CharField(max_length=25, blank=True)
    fringes_taxes_design = models.CharField(max_length=25, blank=True)
    production_designer_units_number = models.CharField(
        max_length=25, blank=True)
    production_designer_units_name = models.CharField(
        max_length=25, blank=True)
    production_designer_rate = models.CharField(max_length=25, blank=True)
    art_director_quantity = models.CharField(max_length=25, blank=True)
    art_director_units_number = models.CharField(max_length=25, blank=True)
    art_director_units_name = models.CharField(max_length=25, blank=True)
    art_director_rate = models.CharField(max_length=25, blank=True)
    art_assistants_quantity = models.CharField(max_length=25, blank=True)
    art_assistants_units_number = models.CharField(max_length=25, blank=True)
    art_assistants_units_name = models.CharField(max_length=25, blank=True)
    art_assistants_rate = models.CharField(max_length=25, blank=True)
    production_assistants_trainees_quantity = models.CharField(
        max_length=25, blank=True)
    production_assistants_trainees_units_number = models.CharField(
        max_length=25, blank=True)
    production_assistants_trainees_units_name = models.CharField(
        max_length=25, blank=True)
    production_assistants_trainees_rate = models.CharField(
        max_length=25, blank=True)
    graphic_artists_quantity = models.CharField(max_length=25, blank=True)
    graphic_artists_units_number = models.CharField(max_length=25, blank=True)
    graphic_artists_units_name = models.CharField(max_length=25, blank=True)
    graphic_artists_rate = models.CharField(max_length=25, blank=True)
    productiondesigner_total = models.CharField(max_length=25, blank=True)
    artdirector_total = models.CharField(max_length=25, blank=True)
    artassistants_total = models.CharField(max_length=25, blank=True)
    productionassistantstrainees_total = models.CharField(
        max_length=25, blank=True)
    graphicartists_total = models.CharField(max_length=25, blank=True)
    other_design = models.CharField(max_length=25, blank=True)
    designlabour_total = models.CharField(max_length=25, blank=True)
    pro_designer_qty_prep = models.CharField(max_length=25, blank=True)
    pro_designer_uno_prep = models.CharField(max_length=25, blank=True)
    pro_designer_una_prep = models.CharField(max_length=25, blank=True)
    pro_designer_rt_prep = models.CharField(max_length=25, blank=True)
    pro_designer_qty_wrap = models.CharField(max_length=25, blank=True)
    pro_designer_uno_wrap = models.CharField(max_length=25, blank=True)
    pro_designer_una_wrap = models.CharField(max_length=25, blank=True)
    pro_designer_rt_wrap = models.CharField(max_length=25, blank=True)
    art_director_qty_prep = models.CharField(max_length=25, blank=True)
    art_director_uno_prep = models.CharField(max_length=25, blank=True)
    art_director_una_prep = models.CharField(max_length=25, blank=True)
    art_director_rt_prep = models.CharField(max_length=25, blank=True)
    art_director_qty_wrap = models.CharField(max_length=25, blank=True)
    art_director_uno_wrap = models.CharField(max_length=25, blank=True)
    art_director_una_wrap = models.CharField(max_length=25, blank=True)
    art_director_rt_wrap = models.CharField(max_length=25, blank=True)
    art_ass_qty_prep = models.CharField(max_length=25, blank=True)
    art_ass_uno_prep = models.CharField(max_length=25, blank=True)
    art_ass_una_prep = models.CharField(max_length=25, blank=True)
    art_ass_rt_prep = models.CharField(max_length=25, blank=True)
    art_ass_qty_wrap = models.CharField(max_length=25, blank=True)
    art_ass_uno_wrap = models.CharField(max_length=25, blank=True)
    art_ass_una_wrap = models.CharField(max_length=25, blank=True)
    art_ass_rt_wrap = models.CharField(max_length=25, blank=True)
    pro_ass_trainees_qty_prep = models.CharField(max_length=25, blank=True)
    pro_ass_trainees_uno_prep = models.CharField(max_length=25, blank=True)
    pro_ass_trainees_una_prep = models.CharField(max_length=25, blank=True)
    pro_ass_trainees_rt_prep = models.CharField(max_length=25, blank=True)
    pro_ass_trainees_qty_wrap = models.CharField(max_length=25, blank=True)
    pro_ass_trainees_uno_wrap = models.CharField(max_length=25, blank=True)
    pro_ass_trainees_una_wrap = models.CharField(max_length=25, blank=True)
    pro_ass_trainees_rt_wrap = models.CharField(max_length=25, blank=True)
    sketch_artists = models.CharField(max_length=25, blank=True)
    sketch_artists_unit = models.CharField(max_length=25, blank=True)
    storyboard_artists = models.CharField(max_length=25, blank=True)
    storyboard_artists_unit = models.CharField(max_length=25, blank=True)
    holidays_design = models.CharField(max_length=25, blank=True)
    holidays_unit_design = models.CharField(max_length=25, blank=True)
    overtime_design = models.CharField(max_length=25, blank=True)
    overtime_unit_design = models.CharField(max_length=25, blank=True)
    days6th7th_design = models.CharField(max_length=25, blank=True)
    days6th7th_unit_design = models.CharField(max_length=25, blank=True)
    box_rent_design = models.CharField(max_length=25, blank=True)
    box_rent_unit_design = models.CharField(max_length=25, blank=True)
    prodesprep_total = models.CharField(max_length=25, blank=True)
    prodeswrap_total = models.CharField(max_length=25, blank=True)
    prodesall_total = models.CharField(max_length=25, blank=True)
    artdirprep_total = models.CharField(max_length=25, blank=True)
    artdirwrap_total = models.CharField(max_length=25, blank=True)
    artdirall_total = models.CharField(max_length=25, blank=True)
    artassprep_total = models.CharField(max_length=25, blank=True)
    artasswrap_total = models.CharField(max_length=25, blank=True)
    artassall_total = models.CharField(max_length=25, blank=True)
    proasstrainprep_total = models.CharField(max_length=25, blank=True)
    proasstrainwrap_total = models.CharField(max_length=25, blank=True)
    proasstrainall_total = models.CharField(max_length=25, blank=True)
    graphicartprep_total = models.CharField(max_length=25, blank=True)
    graphicartall_total = models.CharField(max_length=25, blank=True)
    graphic_art_qty_prep = models.CharField(max_length=25, blank=True)
    graphic_art_uno_prep = models.CharField(max_length=25, blank=True)
    graphic_art_una_prep = models.CharField(max_length=25, blank=True)
    graphic_art_rt_prep = models.CharField(max_length=25, blank=True)
    supervart_qty = models.CharField(max_length=25, blank=True)
    supervart_uno = models.CharField(max_length=25, blank=True)
    supervart_una = models.CharField(max_length=25, blank=True)
    supervart_rt = models.CharField(max_length=25, blank=True)
    supervart_qty_prep = models.CharField(max_length=25, blank=True)
    supervart_uno_prep = models.CharField(max_length=25, blank=True)
    supervart_una_prep = models.CharField(max_length=25, blank=True)
    supervart_rt_prep = models.CharField(max_length=25, blank=True)
    set_design_qty = models.CharField(max_length=25, blank=True)
    set_design_uno = models.CharField(max_length=25, blank=True)
    set_design_una = models.CharField(max_length=25, blank=True)
    set_design_rt = models.CharField(max_length=25, blank=True)
    set_design_qty_prep = models.CharField(max_length=25, blank=True)
    set_design_uno_prep = models.CharField(max_length=25, blank=True)
    set_design_una_prep = models.CharField(max_length=25, blank=True)
    set_design_rt_prep = models.CharField(max_length=25, blank=True)
    junior_draught_qty = models.CharField(max_length=25, blank=True)
    junior_draught_uno = models.CharField(max_length=25, blank=True)
    junior_draught_una = models.CharField(max_length=25, blank=True)
    junior_draught_rt = models.CharField(max_length=25, blank=True)
    junior_draught_qty_prep = models.CharField(max_length=25, blank=True)
    junior_draught_uno_prep = models.CharField(max_length=25, blank=True)
    junior_draught_una_prep = models.CharField(max_length=25, blank=True)
    junior_draught_rt_prep = models.CharField(max_length=25, blank=True)
    standby_art_qty = models.CharField(max_length=25, blank=True)
    standby_art_uno = models.CharField(max_length=25, blank=True)
    standby_art_una = models.CharField(max_length=25, blank=True)
    standby_art_rt = models.CharField(max_length=25, blank=True)
    standby_art_qty_prep = models.CharField(max_length=25, blank=True)
    standby_art_uno_prep = models.CharField(max_length=25, blank=True)
    standby_art_una_prep = models.CharField(max_length=25, blank=True)
    standby_art_rt_prep = models.CharField(max_length=25, blank=True)
    art_dep_coor_qty = models.CharField(max_length=25, blank=True)
    art_dep_coor_uno = models.CharField(max_length=25, blank=True)
    art_dep_coor_una = models.CharField(max_length=25, blank=True)
    art_dep_coor_rt = models.CharField(max_length=25, blank=True)
    art_dep_coor_qty_prep = models.CharField(max_length=25, blank=True)
    art_dep_coor_uno_prep = models.CharField(max_length=25, blank=True)
    art_dep_coor_una_prep = models.CharField(max_length=25, blank=True)
    art_dep_coor_rt_prep = models.CharField(max_length=25, blank=True)
    art_dep_coor_qty_wrap = models.CharField(max_length=25, blank=True)
    art_dep_coor_uno_wrap = models.CharField(max_length=25, blank=True)
    art_dep_coor_una_wrap = models.CharField(max_length=25, blank=True)
    art_dep_coor_rt_wrap = models.CharField(max_length=25, blank=True)
    supartdir_total = models.CharField(max_length=25, blank=True)
    supartdirprep_total = models.CharField(max_length=25, blank=True)
    supartdirall_total = models.CharField(max_length=25, blank=True)
    standbyart_total = models.CharField(max_length=25, blank=True)
    stbyartprep_total = models.CharField(max_length=25, blank=True)
    stbyartall_total = models.CharField(max_length=25, blank=True)
    setdes_total = models.CharField(max_length=25, blank=True)
    setdesprep_total = models.CharField(max_length=25, blank=True)
    setdesall_total = models.CharField(max_length=25, blank=True)
    jundraught_total = models.CharField(max_length=25, blank=True)
    jundraprep_total = models.CharField(max_length=25, blank=True)
    jundraall_total = models.CharField(max_length=25, blank=True)
    artcoor_total = models.CharField(max_length=25, blank=True)
    artcoorprep_total = models.CharField(max_length=25, blank=True)
    artcoorwrap_total = models.CharField(max_length=25, blank=True)
    artcoorall_total = models.CharField(max_length=25, blank=True)
    fringes_taxes_construction = models.CharField(max_length=25, blank=True)
    constructioncoordinator_quantity = models.CharField(
        max_length=25, blank=True)
    constructioncoordinator_units_number = models.CharField(
        max_length=25, blank=True)
    constructioncoordinator_units_name = models.CharField(
        max_length=25, blank=True)
    constructioncoordinator_rate = models.CharField(max_length=25, blank=True)
    headcarpenter_quantity = models.CharField(max_length=25, blank=True)
    headcarpenter_units_number = models.CharField(max_length=25, blank=True)
    headcarpenter_units_name = models.CharField(max_length=25, blank=True)
    headcarpenter_rate = models.CharField(max_length=25, blank=True)
    carpenters_quantity = models.CharField(max_length=25, blank=True)
    carpenters_units_number = models.CharField(max_length=25, blank=True)
    carpenters_units_name = models.CharField(max_length=25, blank=True)
    carpenters_rate = models.CharField(max_length=25, blank=True)
    scenicpainters_quantity = models.CharField(max_length=25, blank=True)
    scenicpainters_units_number = models.CharField(max_length=25, blank=True)
    scenicpainters_units_name = models.CharField(max_length=25, blank=True)
    scenicpainters_rate = models.CharField(max_length=25, blank=True)
    headpainter_quantity = models.CharField(max_length=25, blank=True)
    headpainter_units_number = models.CharField(max_length=25, blank=True)
    headpainter_units_name = models.CharField(max_length=25, blank=True)
    headpainter_rate = models.CharField(max_length=25, blank=True)
    painters_quantity = models.CharField(max_length=25, blank=True)
    painters_units_number = models.CharField(max_length=25, blank=True)
    painters_units_name = models.CharField(max_length=25, blank=True)
    painters_rate = models.CharField(max_length=25, blank=True)
    labourers_quantity = models.CharField(max_length=25, blank=True)
    labourers_units_number = models.CharField(max_length=25, blank=True)
    labourers_units_name = models.CharField(max_length=25, blank=True)
    labourers_rate = models.CharField(max_length=25, blank=True)
    other_construction = models.CharField(max_length=25, blank=True)
    constructioncoordinator_total = models.CharField(max_length=25, blank=True)
    headcarpenter_total = models.CharField(max_length=25, blank=True)
    carpenters_total = models.CharField(max_length=25, blank=True)
    scenicpainters_total = models.CharField(max_length=25, blank=True)
    headpainter_total = models.CharField(max_length=25, blank=True)
    painters_total = models.CharField(max_length=25, blank=True)
    labourers_total = models.CharField(max_length=25, blank=True)
    constructionlabour_total = models.CharField(max_length=25, blank=True)
    days6th7th_unit_con = models.CharField(max_length=25, blank=True)
    days6th7th_con = models.CharField(max_length=25, blank=True)
    overtime_unit_con = models.CharField(max_length=25, blank=True)
    overtime_con = models.CharField(max_length=25, blank=True)
    holidays_unit_con = models.CharField(max_length=25, blank=True)
    holidays_con = models.CharField(max_length=25, blank=True)
    box_rent_unit_con = models.CharField(max_length=25, blank=True)
    box_rent_con = models.CharField(max_length=25, blank=True)
    con_coor_qty_prep = models.CharField(max_length=25, blank=True)
    con_coor_uno_prep = models.CharField(max_length=25, blank=True)
    con_coor_una_prep = models.CharField(max_length=25, blank=True)
    con_coor_rt_prep = models.CharField(max_length=25, blank=True)
    con_coor_qty_wrap = models.CharField(max_length=25, blank=True)
    con_coor_uno_wrap = models.CharField(max_length=25, blank=True)
    con_coor_una_wrap = models.CharField(max_length=25, blank=True)
    con_coor_rt_wrap = models.CharField(max_length=25, blank=True)
    headcar_qty_prep = models.CharField(max_length=25, blank=True)
    headcar_uno_prep = models.CharField(max_length=25, blank=True)
    headcar_una_prep = models.CharField(max_length=25, blank=True)
    headcar_rt_prep = models.CharField(max_length=25, blank=True)
    headcar_qty_wrap = models.CharField(max_length=25, blank=True)
    headcar_uno_wrap = models.CharField(max_length=25, blank=True)
    headcar_una_wrap = models.CharField(max_length=25, blank=True)
    headcar_rt_wrap = models.CharField(max_length=25, blank=True)
    carpen_qty_prep = models.CharField(max_length=25, blank=True)
    carpen_uno_prep = models.CharField(max_length=25, blank=True)
    carpen_una_prep = models.CharField(max_length=25, blank=True)
    carpen_rt_prep = models.CharField(max_length=25, blank=True)
    carpen_qty_wrap = models.CharField(max_length=25, blank=True)
    carpen_uno_wrap = models.CharField(max_length=25, blank=True)
    carpen_una_wrap = models.CharField(max_length=25, blank=True)
    carpen_rt_wrap = models.CharField(max_length=25, blank=True)
    scenic_qty_prep = models.CharField(max_length=25, blank=True)
    scenic_uno_prep = models.CharField(max_length=25, blank=True)
    scenic_una_prep = models.CharField(max_length=25, blank=True)
    scenic_rt_prep = models.CharField(max_length=25, blank=True)
    scenic_qty_wrap = models.CharField(max_length=25, blank=True)
    scenic_uno_wrap = models.CharField(max_length=25, blank=True)
    scenic_una_wrap = models.CharField(max_length=25, blank=True)
    scenic_rt_wrap = models.CharField(max_length=25, blank=True)
    headpain_qty_prep = models.CharField(max_length=25, blank=True)
    headpain_uno_prep = models.CharField(max_length=25, blank=True)
    headpain_una_prep = models.CharField(max_length=25, blank=True)
    headpain_rt_prep = models.CharField(max_length=25, blank=True)
    headpain_qty_wrap = models.CharField(max_length=25, blank=True)
    headpain_uno_wrap = models.CharField(max_length=25, blank=True)
    headpain_una_wrap = models.CharField(max_length=25, blank=True)
    headpain_rt_wrap = models.CharField(max_length=25, blank=True)
    pain_qty_prep = models.CharField(max_length=25, blank=True)
    pain_uno_prep = models.CharField(max_length=25, blank=True)
    pain_una_prep = models.CharField(max_length=25, blank=True)
    pain_rt_prep = models.CharField(max_length=25, blank=True)
    pain_qty_wrap = models.CharField(max_length=25, blank=True)
    pain_uno_wrap = models.CharField(max_length=25, blank=True)
    pain_una_wrap = models.CharField(max_length=25, blank=True)
    pain_rt_wrap = models.CharField(max_length=25, blank=True)
    labo_qty_prep = models.CharField(max_length=25, blank=True)
    labo_uno_prep = models.CharField(max_length=25, blank=True)
    labo_una_prep = models.CharField(max_length=25, blank=True)
    labo_rt_prep = models.CharField(max_length=25, blank=True)
    labo_qty_wrap = models.CharField(max_length=25, blank=True)
    labo_uno_wrap = models.CharField(max_length=25, blank=True)
    labo_una_wrap = models.CharField(max_length=25, blank=True)
    labo_rt_wrap = models.CharField(max_length=25, blank=True)
    concoorprep_total = models.CharField(max_length=25, blank=True)
    concoorwrap_total = models.CharField(max_length=25, blank=True)
    concoorall_total = models.CharField(max_length=25, blank=True)
    headcarprep_total = models.CharField(max_length=25, blank=True)
    headcarwrap_total = models.CharField(max_length=25, blank=True)
    headcarall_total = models.CharField(max_length=25, blank=True)
    carpenprep_total = models.CharField(max_length=25, blank=True)
    carpenwrap_total = models.CharField(max_length=25, blank=True)
    carpenall_total = models.CharField(max_length=25, blank=True)
    scenicprep_total = models.CharField(max_length=25, blank=True)
    scenicwrap_total = models.CharField(max_length=25, blank=True)
    scenicall_total = models.CharField(max_length=25, blank=True)
    headpainprep_total = models.CharField(max_length=25, blank=True)
    headpainwrap_total = models.CharField(max_length=25, blank=True)
    headpainall_total = models.CharField(max_length=25, blank=True)
    paintprep_total = models.CharField(max_length=25, blank=True)
    paintwrap_total = models.CharField(max_length=25, blank=True)
    paintall_total = models.CharField(max_length=25, blank=True)
    laboprep_total = models.CharField(max_length=25, blank=True)
    labowrap_total = models.CharField(max_length=25, blank=True)
    laboall_total = models.CharField(max_length=25, blank=True)
    set_decorator_quantity = models.CharField(max_length=25, blank=True)
    set_decorator_units_number = models.CharField(max_length=25, blank=True)
    set_decorator_units_name = models.CharField(max_length=25, blank=True)
    set_decorator_rate = models.CharField(max_length=25, blank=True)
    assist_set_decorator_quantity = models.CharField(max_length=25, blank=True)
    assist_set_decorator_units_number = models.CharField(
        max_length=25, blank=True)
    assist_set_decorator_units_name = models.CharField(
        max_length=25, blank=True)
    assist_set_decorator_rate = models.CharField(max_length=25, blank=True)
    lead_man_quantity = models.CharField(max_length=25, blank=True)
    lead_man_units_number = models.CharField(max_length=25, blank=True)
    lead_man_units_name = models.CharField(max_length=25, blank=True)
    lead_man_rate = models.CharField(max_length=25, blank=True)
    set_dressers_quantity = models.CharField(max_length=25, blank=True)
    set_dressers_units_number = models.CharField(max_length=25, blank=True)
    set_dressers_units_name = models.CharField(max_length=25, blank=True)
    set_dressers_rate = models.CharField(max_length=25, blank=True)
    swing_gang_quantity = models.CharField(max_length=25, blank=True)
    swing_gang_units_number = models.CharField(max_length=25, blank=True)
    swing_gang_units_name = models.CharField(max_length=25, blank=True)
    swing_gang_rate = models.CharField(max_length=25, blank=True)
    set_dressing_buyer_quantity = models.CharField(max_length=25, blank=True)
    set_dressing_buyer_units_number = models.CharField(
        max_length=25, blank=True)
    set_dressing_buyer_units_name = models.CharField(max_length=25, blank=True)
    set_dressing_buyer_rate = models.CharField(max_length=25, blank=True)
    other_set_dressing = models.CharField(max_length=25, blank=True)
    decoratorset_total = models.CharField(max_length=25, blank=True)
    assistdecoratorset_total = models.CharField(max_length=25, blank=True)
    leadman_total = models.CharField(max_length=25, blank=True)
    dressers_total = models.CharField(max_length=25, blank=True)
    swinggang_total = models.CharField(max_length=25, blank=True)
    dressingbuyer_total = models.CharField(max_length=25, blank=True)
    dressinglabour_total = models.CharField(max_length=25, blank=True)
    days6th7th_unit_dres = models.CharField(max_length=25, blank=True)
    days6th7th_dres = models.CharField(max_length=25, blank=True)
    overtime_unit_dres = models.CharField(max_length=25, blank=True)
    overtime_dres = models.CharField(max_length=25, blank=True)
    holidays_unit_dres = models.CharField(max_length=25, blank=True)
    holidays_dres = models.CharField(max_length=25, blank=True)
    box_rent_unit_dres = models.CharField(max_length=25, blank=True)
    box_rent_dres = models.CharField(max_length=25, blank=True)
    set_dec_qty_prep = models.CharField(max_length=25, blank=True)
    set_dec_uno_prep = models.CharField(max_length=25, blank=True)
    set_dec_una_prep = models.CharField(max_length=25, blank=True)
    set_dec_rt_prep = models.CharField(max_length=25, blank=True)
    set_dec_qty_wrap = models.CharField(max_length=25, blank=True)
    set_dec_uno_wrap = models.CharField(max_length=25, blank=True)
    set_dec_una_wrap = models.CharField(max_length=25, blank=True)
    set_dec_rt_wrap = models.CharField(max_length=25, blank=True)
    ass_set_d_qty_prep = models.CharField(max_length=25, blank=True)
    ass_set_d_uno_prep = models.CharField(max_length=25, blank=True)
    ass_set_d_una_prep = models.CharField(max_length=25, blank=True)
    ass_set_d_rt_prep = models.CharField(max_length=25, blank=True)
    ass_set_d_qty_wrap = models.CharField(max_length=25, blank=True)
    ass_set_d_uno_wrap = models.CharField(max_length=25, blank=True)
    ass_set_d_una_wrap = models.CharField(max_length=25, blank=True)
    ass_set_d_rt_wrap = models.CharField(max_length=25, blank=True)
    lead_man_qty_prep = models.CharField(max_length=25, blank=True)
    lead_man_uno_prep = models.CharField(max_length=25, blank=True)
    lead_man_una_prep = models.CharField(max_length=25, blank=True)
    lead_man_rt_prep = models.CharField(max_length=25, blank=True)
    lead_man_qty_wrap = models.CharField(max_length=25, blank=True)
    lead_man_uno_wrap = models.CharField(max_length=25, blank=True)
    lead_man_una_wrap = models.CharField(max_length=25, blank=True)
    lead_man_rt_wrap = models.CharField(max_length=25, blank=True)
    set_dres_qty_prep = models.CharField(max_length=25, blank=True)
    set_dres_uno_prep = models.CharField(max_length=25, blank=True)
    set_dres_una_prep = models.CharField(max_length=25, blank=True)
    set_dres_rt_prep = models.CharField(max_length=25, blank=True)
    set_dres_qty_wrap = models.CharField(max_length=25, blank=True)
    set_dres_uno_wrap = models.CharField(max_length=25, blank=True)
    set_dres_una_wrap = models.CharField(max_length=25, blank=True)
    set_dres_rt_wrap = models.CharField(max_length=25, blank=True)
    swing_g_qty_prep = models.CharField(max_length=25, blank=True)
    swing_g_uno_prep = models.CharField(max_length=25, blank=True)
    swing_g_una_prep = models.CharField(max_length=25, blank=True)
    swing_g_rt_prep = models.CharField(max_length=25, blank=True)
    swing_g_qty_wrap = models.CharField(max_length=25, blank=True)
    swing_g_uno_wrap = models.CharField(max_length=25, blank=True)
    swing_g_una_wrap = models.CharField(max_length=25, blank=True)
    swing_g_rt_wrap = models.CharField(max_length=25, blank=True)
    set_d_buy_qty_prep = models.CharField(max_length=25, blank=True)
    set_d_buy_uno_prep = models.CharField(max_length=25, blank=True)
    set_d_buy_una_prep = models.CharField(max_length=25, blank=True)
    set_d_buy_rt_prep = models.CharField(max_length=25, blank=True)
    set_d_buy_qty_wrap = models.CharField(max_length=25, blank=True)
    set_d_buy_uno_wrap = models.CharField(max_length=25, blank=True)
    set_d_buy_una_wrap = models.CharField(max_length=25, blank=True)
    set_d_buy_rt_wrap = models.CharField(max_length=25, blank=True)
    decsetprep_total = models.CharField(max_length=25, blank=True)
    decsetwrap_total = models.CharField(max_length=25, blank=True)
    decsetall_total = models.CharField(max_length=25, blank=True)
    assdsetprep_total = models.CharField(max_length=25, blank=True)
    assdsetwrap_total = models.CharField(max_length=25, blank=True)
    assdsetall_total = models.CharField(max_length=25, blank=True)
    leadmanprep_total = models.CharField(max_length=25, blank=True)
    leadmanwrap_total = models.CharField(max_length=25, blank=True)
    leadmanall_total = models.CharField(max_length=25, blank=True)
    dressprep_total = models.CharField(max_length=25, blank=True)
    dresswrap_total = models.CharField(max_length=25, blank=True)
    dressall_total = models.CharField(max_length=25, blank=True)
    swinggprep_total = models.CharField(max_length=25, blank=True)
    swinggwrap_total = models.CharField(max_length=25, blank=True)
    swinggall_total = models.CharField(max_length=25, blank=True)
    dressbuyprep_total = models.CharField(max_length=25, blank=True)
    dressbuywrap_total = models.CharField(max_length=25, blank=True)
    dressbuyall_total = models.CharField(max_length=25, blank=True)
    property_master_quantity = models.CharField(max_length=25, blank=True)
    property_master_units_number = models.CharField(max_length=25, blank=True)
    property_master_units_name = models.CharField(max_length=25, blank=True)
    property_master_rate = models.CharField(max_length=25, blank=True)
    assist_property_master_quantity = models.CharField(
        max_length=25, blank=True)
    assist_property_master_units_number = models.CharField(
        max_length=25, blank=True)
    assist_property_master_units_name = models.CharField(
        max_length=25, blank=True)
    assist_property_master_rate = models.CharField(max_length=25, blank=True)
    on_set_props_person_quantity = models.CharField(max_length=25, blank=True)
    on_set_props_person_units_number = models.CharField(
        max_length=25, blank=True)
    on_set_props_person_units_name = models.CharField(
        max_length=25, blank=True)
    on_set_props_person_rate = models.CharField(max_length=25, blank=True)
    property_buyer_quantity = models.CharField(max_length=25, blank=True)
    property_buyer_units_number = models.CharField(max_length=25, blank=True)
    property_buyer_units_name = models.CharField(max_length=25, blank=True)
    property_buyer_rate = models.CharField(max_length=25, blank=True)
    armorer_quantity = models.CharField(max_length=25, blank=True)
    armorer_units_number = models.CharField(max_length=25, blank=True)
    armorer_units_name = models.CharField(max_length=25, blank=True)
    armorer_rate = models.CharField(max_length=25, blank=True)
    other_property = models.CharField(max_length=25, blank=True)
    propertymaster_total = models.CharField(max_length=25, blank=True)
    assistpropertymaster_total = models.CharField(max_length=25, blank=True)
    onsetpropsperson_total = models.CharField(max_length=25, blank=True)
    propertybuyer_total = models.CharField(max_length=25, blank=True)
    armorer_total = models.CharField(max_length=25, blank=True)
    propertylabour_total = models.CharField(max_length=25, blank=True)
    days6th7th_unit_prop = models.CharField(max_length=25, blank=True)
    days6th7th_prop = models.CharField(max_length=25, blank=True)
    overtime_unit_prop = models.CharField(max_length=25, blank=True)
    overtime_prop = models.CharField(max_length=25, blank=True)
    holidays_unit_prop = models.CharField(max_length=25, blank=True)
    holidays_prop = models.CharField(max_length=25, blank=True)
    box_rent_unit_prop = models.CharField(max_length=25, blank=True)
    box_rent_prop = models.CharField(max_length=25, blank=True)
    pro_mas_qty_prep = models.CharField(max_length=25, blank=True)
    pro_mas_uno_prep = models.CharField(max_length=25, blank=True)
    pro_mas_una_prep = models.CharField(max_length=25, blank=True)
    pro_mas_rt_prep = models.CharField(max_length=25, blank=True)
    pro_mas_qty_wrap = models.CharField(max_length=25, blank=True)
    pro_mas_uno_wrap = models.CharField(max_length=25, blank=True)
    pro_mas_una_wrap = models.CharField(max_length=25, blank=True)
    pro_mas_rt_wrap = models.CharField(max_length=25, blank=True)
    as_pro_ma_qty_prep = models.CharField(max_length=25, blank=True)
    as_pro_ma_uno_prep = models.CharField(max_length=25, blank=True)
    as_pro_ma_una_prep = models.CharField(max_length=25, blank=True)
    as_pro_ma_rt_prep = models.CharField(max_length=25, blank=True)
    as_pro_ma_qty_wrap = models.CharField(max_length=25, blank=True)
    as_pro_ma_uno_wrap = models.CharField(max_length=25, blank=True)
    as_pro_ma_una_wrap = models.CharField(max_length=25, blank=True)
    as_pro_ma_rt_wrap = models.CharField(max_length=25, blank=True)
    on_set_prop_qty_prep = models.CharField(max_length=25, blank=True)
    on_set_prop_uno_prep = models.CharField(max_length=25, blank=True)
    on_set_prop_una_prep = models.CharField(max_length=25, blank=True)
    on_set_prop_rt_prep = models.CharField(max_length=25, blank=True)
    on_set_prop_qty_wrap = models.CharField(max_length=25, blank=True)
    on_set_prop_uno_wrap = models.CharField(max_length=25, blank=True)
    on_set_prop_una_wrap = models.CharField(max_length=25, blank=True)
    on_set_prop_rt_wrap = models.CharField(max_length=25, blank=True)
    prop_buy_qty_prep = models.CharField(max_length=25, blank=True)
    prop_buy_uno_prep = models.CharField(max_length=25, blank=True)
    prop_buy_una_prep = models.CharField(max_length=25, blank=True)
    prop_buy_rt_prep = models.CharField(max_length=25, blank=True)
    prop_buy_qty_wrap = models.CharField(max_length=25, blank=True)
    prop_buy_uno_wrap = models.CharField(max_length=25, blank=True)
    prop_buy_una_wrap = models.CharField(max_length=25, blank=True)
    prop_buy_rt_wrap = models.CharField(max_length=25, blank=True)
    armor_qty_prep = models.CharField(max_length=25, blank=True)
    armor_uno_prep = models.CharField(max_length=25, blank=True)
    armor_una_prep = models.CharField(max_length=25, blank=True)
    armor_rt_prep = models.CharField(max_length=25, blank=True)
    armor_qty_wrap = models.CharField(max_length=25, blank=True)
    armor_uno_wrap = models.CharField(max_length=25, blank=True)
    armor_una_wrap = models.CharField(max_length=25, blank=True)
    armor_rt_wrap = models.CharField(max_length=25, blank=True)
    propmasprep_total = models.CharField(max_length=25, blank=True)
    propmaswrap_total = models.CharField(max_length=25, blank=True)
    propmasall_total = models.CharField(max_length=25, blank=True)
    aspropmaprep_total = models.CharField(max_length=25, blank=True)
    aspropmawrap_total = models.CharField(max_length=25, blank=True)
    aspropmaall_total = models.CharField(max_length=25, blank=True)
    onsetpropprep_total = models.CharField(max_length=25, blank=True)
    onsetpropwrap_total = models.CharField(max_length=25, blank=True)
    onsetpropall_total = models.CharField(max_length=25, blank=True)
    propbuyprep_total = models.CharField(max_length=25, blank=True)
    propbuywrap_total = models.CharField(max_length=25, blank=True)
    propbuyall_total = models.CharField(max_length=25, blank=True)
    armorprep_total = models.CharField(max_length=25, blank=True)
    armorwrap_total = models.CharField(max_length=25, blank=True)
    armorall_total = models.CharField(max_length=25, blank=True)   
    fringes_taxes_dressing = models.CharField(max_length=25, blank=True)
    fringes_taxes_property = models.CharField(max_length=25, blank=True)

    class Meta:
        """ Meta for ordering """
        ordering = ['-created_at']

    def __str__(self):
        return f"{self.title} "
