# Generated by Django 3.2.15 on 2024-02-24 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets3', '0002_budget3_budget_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget3',
            name='audall_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='audio_qty',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='audio_qty_prep',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='audio_qty_wrap',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='audio_rt',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='audio_rt_prep',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='audio_rt_wrap',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='audio_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='audio_una',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='audio_una_prep',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='audio_una_wrap',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='audio_uno',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='audio_uno_prep',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='audio_uno_wrap',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='audprep_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='audwrap_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='boamanall_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='boamanprep_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='boamanwrap_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='boardm_qty_prep',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='boardm_qty_wrap',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='boardm_rt_prep',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='boardm_rt_wrap',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='boardm_una_prep',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='boardm_una_wrap',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='boardm_uno_prep',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='boardm_uno_wrap',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='boardman_qty',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='boardman_rt',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='boardman_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='boardman_una',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='boardman_uno',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='box_rent_tran',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='box_rent_tv',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='box_rent_unit_tran',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='box_rent_unit_tv',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='days6th7th_tran',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='days6th7th_tv',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='days6th7th_unit_tran',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='days6th7th_unit_tv',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='drive_qty_prep',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='drive_qty_wrap',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='drive_rt_prep',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='drive_rt_wrap',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='drive_una_prep',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='drive_una_wrap',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='drive_uno_prep',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='drive_uno_wrap',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='driverall_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='driverprep_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='drivers_qty',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='drivers_rt',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='drivers_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='drivers_una',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='drivers_uno',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='driverwrap_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='flo_man_qty_prep',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='flo_man_qty_wrap',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='flo_man_rt_prep',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='flo_man_rt_wrap',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='flo_man_una_prep',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='flo_man_una_wrap',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='flo_man_uno_prep',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='flo_man_uno_wrap',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='flomanall_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='flomanprep_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='flomanwrap_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='floor_man_qty',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='floor_man_rt',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='floor_man_una',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='floor_man_uno',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='floorman_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='fringes_taxes_transport',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='fringes_taxes_tv',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='head_dr_qty_prep',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='head_dr_qty_wrap',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='head_dr_rt_prep',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='head_dr_rt_wrap',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='head_dr_una_prep',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='head_dr_una_wrap',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='head_dr_uno_prep',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='head_dr_uno_wrap',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='head_driver_qty',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='head_driver_rt',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='head_driver_una',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='head_driver_uno',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='headdriall_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='headdriprep_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='headdriver_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='headdriwrap_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='holidays_tran',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='holidays_tv',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='holidays_unit_tran',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='holidays_unit_tv',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='lig_dir_qty_prep',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='lig_dir_qty_wrap',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='lig_dir_rt_prep',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='lig_dir_rt_wrap',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='lig_dir_una_prep',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='lig_dir_una_wrap',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='lig_dir_uno_prep',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='lig_dir_uno_wrap',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='ligdirall_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='ligdirprep_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='ligdirwrap_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='light_direct_qty',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='light_direct_rt',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='light_direct_una',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='light_direct_uno',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='lightdirect_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='oth_tv_qty_prep',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='oth_tv_qty_wrap',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='oth_tv_rt_prep',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='oth_tv_rt_wrap',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='oth_tv_una_prep',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='oth_tv_una_wrap',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='oth_tv_uno_prep',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='oth_tv_uno_wrap',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='other_solo_tran',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='other_solo_tv',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='other_tv_qty',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='other_tv_rt',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='other_tv_una',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='other_tv_uno',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='othertv_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='othtvall_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='othtvprep_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='othtvwrap_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='overtime_tran',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='overtime_tv',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='overtime_unit_tran',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='overtime_unit_tv',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='stageh_qty_prep',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='stageh_qty_wrap',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='stageh_rt_prep',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='stageh_rt_wrap',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='stageh_una_prep',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='stageh_una_wrap',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='stageh_uno_prep',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='stageh_uno_wrap',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='stagehall_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='stagehands_qty',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='stagehands_rt',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='stagehands_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='stagehands_una',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='stagehands_uno',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='stagehprep_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='stagehwrap_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='tec_dir_qty_prep',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='tec_dir_qty_wrap',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='tec_dir_rt_prep',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='tec_dir_rt_wrap',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='tec_dir_una_prep',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='tec_dir_una_wrap',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='tec_dir_uno_prep',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='tec_dir_uno_wrap',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='tec_sup_qty_prep',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='tec_sup_qty_wrap',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='tec_sup_rt_prep',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='tec_sup_rt_wrap',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='tec_sup_una_prep',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='tec_sup_una_wrap',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='tec_sup_uno_prep',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='tec_sup_uno_wrap',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='tecdirall_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='tecdirprep_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='tecdirwrap_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='tech_direct_qty',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='tech_direct_rt',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='tech_direct_una',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='tech_direct_uno',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='tech_super_qty',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='tech_super_rt',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='tech_super_una',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='tech_super_uno',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='techdirect_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='techsuper_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='tecsupall_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='tecsupprep_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='tecsupwrap_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='tp_cap_qty_prep',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='tp_cap_qty_wrap',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='tp_cap_rt_prep',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='tp_cap_rt_wrap',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='tp_cap_una_prep',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='tp_cap_una_wrap',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='tp_cap_uno_prep',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='tp_cap_uno_wrap',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='tp_captain_qty',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='tp_captain_rt',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='tp_captain_una',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='tp_captain_uno',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='tp_coor_qty_prep',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='tp_coor_qty_wrap',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='tp_coor_rt_prep',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='tp_coor_rt_wrap',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='tp_coor_una_prep',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='tp_coor_una_wrap',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='tp_coor_uno_prep',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='tp_coor_uno_wrap',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='tp_coordinator_qty',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='tp_coordinator_rt',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='tp_coordinator_una',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='tp_coordinator_uno',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='tp_man_qty_prep',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='tp_man_qty_wrap',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='tp_man_rt_prep',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='tp_man_rt_wrap',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='tp_man_una_prep',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='tp_man_una_wrap',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='tp_man_uno_prep',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='tp_man_uno_wrap',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='tp_manager_qty',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='tp_manager_rt',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='tp_manager_una',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='tp_manager_uno',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='tpcapall_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='tpcapprep_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='tpcaptain_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='tpcapwrap_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='tpcoorall_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='tpcoordinator_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='tpcoorprep_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='tpcoorwrap_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='tpmanager_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='tpmanall_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='tpmanprep_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='tpmanwrap_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='transportlabour_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='tvspecificlabour_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='vtr_op_qty_prep',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='vtr_op_qty_wrap',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='vtr_op_rt_prep',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='vtr_op_rt_wrap',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='vtr_op_una_prep',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='vtr_op_una_wrap',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='vtr_op_uno_prep',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='vtr_op_uno_wrap',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='vtr_operator_qty',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='vtr_operator_rt',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='vtr_operator_una',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='vtr_operator_uno',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='vtropall_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='vtroperator_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='vtropprep_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget3',
            name='vtropwrap_total',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
