"""
Models for Budgets App
"""
from django.db import models
from django.contrib.auth.models import User


class Budget(models.Model):
    """
    Budget model
    """
    project = models.CharField(max_length=25, blank=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    title = models.CharField(max_length=25, blank=True)
    series = models.CharField(max_length=25, blank=True)
    prodco = models.CharField(max_length=25, blank=True)
    format = models.CharField(max_length=25, blank=True)
    location = models.CharField(max_length=25, blank=True)
    dated = models.CharField(max_length=25, blank=True)
    writer = models.CharField(max_length=25, blank=True)
    prelimfin = models.CharField(max_length=25, blank=True)
    preparedby = models.CharField(max_length=25, blank=True)
    approvedby = models.CharField(max_length=25, blank=True)
    approvedbyco = models.CharField(max_length=25, blank=True)
    research = models.CharField(max_length=25, blank=True)
    prep = models.CharField(max_length=25, blank=True)
    shoot = models.CharField(max_length=25, blank=True)
    wrap = models.CharField(max_length=25, blank=True)
    post = models.CharField(max_length=25, blank=True)
    length_total = models.CharField(max_length=25, blank=True)
    story_rights = models.CharField(max_length=25, blank=True)
    miscellaneous = models.CharField(max_length=25, blank=True)
    rights_total = models.CharField(max_length=25, blank=True)
    research_development = models.CharField(max_length=25, blank=True)
    prelim_budget = models.CharField(max_length=25, blank=True)
    consultant_expenses = models.CharField(max_length=25, blank=True)
    office_expenses = models.CharField(max_length=25, blank=True)
    staff = models.CharField(max_length=25, blank=True)
    travel_expenses_development = models.CharField(max_length=25, blank=True)
    living_expenses_development = models.CharField(max_length=25, blank=True)
    other_development = models.CharField(max_length=25, blank=True)
    development_total = models.CharField(max_length=25, blank=True)
    writers_quantity = models.CharField(max_length=25, blank=True)
    writers_units_number = models.CharField(max_length=25, blank=True)
    writers_units_name = models.CharField(max_length=25, blank=True)
    writers_rate = models.CharField(max_length=25, blank=True)
    writers_total = models.CharField(max_length=25, blank=True)
    consultants_quantity = models.CharField(max_length=25, blank=True)
    consultants_units_number = models.CharField(max_length=25, blank=True)
    consultants_units_name = models.CharField(max_length=25, blank=True)
    consultants_rate = models.CharField(max_length=25, blank=True)
    consultants_total = models.CharField(max_length=25, blank=True)
    editors_scenario_quantity = models.CharField(max_length=25, blank=True)
    editors_scenario_units_number = models.CharField(max_length=25, blank=True)
    editors_scenario_units_name = models.CharField(max_length=25, blank=True)
    editors_scenario_rate = models.CharField(max_length=25, blank=True)
    editors_scenario_total = models.CharField(max_length=25, blank=True)
    admin_scenario_quantity = models.CharField(max_length=25, blank=True)
    admin_scenario_units_number = models.CharField(max_length=25, blank=True)
    admin_scenario_units_name = models.CharField(max_length=25, blank=True)
    admin_scenario_rate = models.CharField(max_length=25, blank=True)
    admin_scenario_total = models.CharField(max_length=25, blank=True)
    office_expenses_scenario = models.CharField(max_length=25, blank=True)
    travel_expenses_scenario = models.CharField(max_length=25, blank=True)
    living_expenses_scenario = models.CharField(max_length=25, blank=True)
    other_scenario = models.CharField(max_length=25, blank=True)
    scenario_total = models.CharField(max_length=25, blank=True)
    executive_producers_quantity = models.CharField(max_length=25, blank=True)
    producers_quantity = models.CharField(max_length=25, blank=True)
    line_producers_quantity = models.CharField(max_length=25, blank=True)
    co_producers_quantity = models.CharField(max_length=25, blank=True)
    associate_producers_quantity = models.CharField(max_length=25, blank=True)
    directors_quantity = models.CharField(max_length=25, blank=True)
    unit2_directors_quantity = models.CharField(max_length=25, blank=True)
    executive_producers_rate = models.CharField(max_length=25, blank=True)
    producers_rate = models.CharField(max_length=25, blank=True)
    line_producers_rate = models.CharField(max_length=25, blank=True)
    co_producers_rate = models.CharField(max_length=25, blank=True)
    associate_producers_rate = models.CharField(max_length=25, blank=True)
    directors_rate = models.CharField(max_length=25, blank=True)
    unit2_directors_rate = models.CharField(max_length=25, blank=True)
    executive_producers_total = models.CharField(max_length=25, blank=True)
    producers_total = models.CharField(max_length=25, blank=True)
    line_producers_total = models.CharField(max_length=25, blank=True)
    co_producers_total = models.CharField(max_length=25, blank=True)
    associate_producers_total = models.CharField(max_length=25, blank=True)
    directors_total = models.CharField(max_length=25, blank=True)
    unit2_directors_total = models.CharField(max_length=25, blank=True)
    travel_expenses_producers_dirs = models.CharField(
        max_length=25, blank=True)
    living_expenses_producers_dirs = models.CharField(
        max_length=25, blank=True)
    other_producers_dirs = models.CharField(max_length=25, blank=True)
    fringes_taxes_producers_dirs = models.CharField(max_length=25, blank=True)
    producers_dirs_total = models.CharField(max_length=25, blank=True)
    stars = models.CharField(max_length=25, blank=True)
    stars_rights_payments = models.CharField(max_length=25, blank=True)
    travel_expenses_stars = models.CharField(max_length=25, blank=True)
    living_expenses_stars = models.CharField(max_length=25, blank=True)
    other_stars = models.CharField(max_length=25, blank=True)
    fringes_taxes_stars = models.CharField(max_length=25, blank=True)
    music = models.CharField(max_length=25, blank=True)
    music_supervisor = models.CharField(max_length=25, blank=True)
    travel_expenses_music = models.CharField(max_length=25, blank=True)
    living_expenses_music = models.CharField(max_length=25, blank=True)
    music_rights_addl_songs = models.CharField(max_length=25, blank=True)
    other_music = models.CharField(max_length=25, blank=True)
    fringes_taxes_music = models.CharField(max_length=25, blank=True)
    stars_music_total = models.CharField(max_length=25, blank=True)
    above_the_line_total = models.CharField(max_length=25, blank=True)
    principals_quantity = models.CharField(max_length=25, blank=True)
    principals_units_number = models.CharField(max_length=25, blank=True)
    principals_units_name = models.CharField(max_length=25, blank=True)
    principals_rate = models.CharField(max_length=25, blank=True)
    actors_quantity = models.CharField(max_length=25, blank=True)
    actors_units_number = models.CharField(max_length=25, blank=True)
    actors_units_name = models.CharField(max_length=25, blank=True)
    actors_rate = models.CharField(max_length=25, blank=True)
    stuntcoordinators_quantity = models.CharField(max_length=25, blank=True)
    stuntcoordinators_units_number = models.CharField(
        max_length=25, blank=True)
    stuntcoordinators_units_name = models.CharField(max_length=25, blank=True)
    stuntcoordinators_rate = models.CharField(max_length=25, blank=True)
    stuntperformers_quantity = models.CharField(max_length=25, blank=True)
    stuntperformers_units_number = models.CharField(max_length=25, blank=True)
    stuntperformers_units_name = models.CharField(max_length=25, blank=True)
    stuntperformers_rate = models.CharField(max_length=25, blank=True)
    otherperformers_quantity = models.CharField(max_length=25, blank=True)
    otherperformers_units_number = models.CharField(max_length=25, blank=True)
    otherperformers_units_name = models.CharField(max_length=25, blank=True)
    otherperformers_rate = models.CharField(max_length=25, blank=True)
    extras_quantity = models.CharField(max_length=25, blank=True)
    extras_units_number = models.CharField(max_length=25, blank=True)
    extras_units_name = models.CharField(max_length=25, blank=True)
    extras_rate = models.CharField(max_length=25, blank=True)
    principals_total = models.CharField(max_length=25, blank=True)
    actors_total = models.CharField(max_length=25, blank=True)
    stuntcoordinators_total = models.CharField(max_length=25, blank=True)
    stuntperformers_total = models.CharField(max_length=25, blank=True)
    otherperformers_total = models.CharField(max_length=25, blank=True)
    extras_total = models.CharField(max_length=25, blank=True)
    casting_director = models.CharField(max_length=25, blank=True)
    extras_casting = models.CharField(max_length=25, blank=True)
    other_cast = models.CharField(max_length=25, blank=True)
    fringes_taxes_cast = models.CharField(max_length=25, blank=True)
    rights_payments_cast = models.CharField(max_length=25, blank=True)
    cast_total = models.CharField(max_length=25, blank=True)

    class Meta:
        """ Meta for ordering """
        ordering = ['-created_at']

    def __str__(self):
        return f"{self.title} "
