"""
Models for Budgets App
"""
from django.db import models
from django.contrib.auth.models import User


class Budget(models.Model):
    """
    Budget model
    """
    project = models.CharField(max_length=25, blank=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    above_the_line_total = models.CharField(max_length=25, blank=True)
    below_the_lineB_total = models.CharField(max_length=25, blank=True)
    grand_total = models.CharField(max_length=25, blank=True)
    title = models.CharField(max_length=25, blank=True)
    series = models.CharField(max_length=25, blank=True)
    prodco = models.CharField(max_length=25, blank=True)
    format = models.CharField(max_length=25, blank=True)
    location = models.CharField(max_length=25, blank=True)
    dated = models.CharField(max_length=25, blank=True)
    writer = models.CharField(max_length=25, blank=True)
    prelimfin = models.CharField(max_length=25, blank=True)
    preparedby = models.CharField(max_length=25, blank=True)
    approvedby = models.CharField(max_length=25, blank=True)
    approvedbyco = models.CharField(max_length=25, blank=True)
    research = models.CharField(max_length=25, blank=True)
    prep = models.CharField(max_length=25, blank=True)
    shoot = models.CharField(max_length=25, blank=True)
    wrap = models.CharField(max_length=25, blank=True)
    post = models.CharField(max_length=25, blank=True)
    length_total = models.CharField(max_length=25, blank=True)
    story_rights = models.CharField(max_length=25, blank=True)
    miscellaneous = models.CharField(max_length=25, blank=True)
    rights_total = models.CharField(max_length=25, blank=True)
    research_development = models.CharField(max_length=25, blank=True)
    prelim_budget = models.CharField(max_length=25, blank=True)
    consultant_expenses = models.CharField(max_length=25, blank=True)
    office_expenses = models.CharField(max_length=25, blank=True)
    staff = models.CharField(max_length=25, blank=True)
    travel_expenses_development = models.CharField(max_length=25, blank=True)
    living_expenses_development = models.CharField(max_length=25, blank=True)
    other_development = models.CharField(max_length=25, blank=True)
    fringes_taxes_development = models.CharField(max_length=25, blank=True)
    development_total = models.CharField(max_length=25, blank=True)
    writers_quantity = models.CharField(max_length=25, blank=True)
    writers_units_number = models.CharField(max_length=25, blank=True)
    writers_units_name = models.CharField(max_length=25, blank=True)
    writers_rate = models.CharField(max_length=25, blank=True)
    writers_total = models.CharField(max_length=25, blank=True)
    consultants_quantity = models.CharField(max_length=25, blank=True)
    consultants_units_number = models.CharField(max_length=25, blank=True)
    consultants_units_name = models.CharField(max_length=25, blank=True)
    consultants_rate = models.CharField(max_length=25, blank=True)
    consultants_total = models.CharField(max_length=25, blank=True)
    editors_scenario_quantity = models.CharField(max_length=25, blank=True)
    editors_scenario_units_number = models.CharField(max_length=25, blank=True)
    editors_scenario_units_name = models.CharField(max_length=25, blank=True)
    editors_scenario_rate = models.CharField(max_length=25, blank=True)
    editors_scenario_total = models.CharField(max_length=25, blank=True)
    admin_scenario_quantity = models.CharField(max_length=25, blank=True)
    admin_scenario_units_number = models.CharField(max_length=25, blank=True)
    admin_scenario_units_name = models.CharField(max_length=25, blank=True)
    admin_scenario_rate = models.CharField(max_length=25, blank=True)
    admin_scenario_total = models.CharField(max_length=25, blank=True)
    office_expenses_scenario = models.CharField(max_length=25, blank=True)
    travel_expenses_scenario = models.CharField(max_length=25, blank=True)
    living_expenses_scenario = models.CharField(max_length=25, blank=True)
    other_scenario = models.CharField(max_length=25, blank=True)
    fringes_taxes_scenario = models.CharField(max_length=25, blank=True)
    scenario_total = models.CharField(max_length=25, blank=True)
    executive_producers_quantity = models.CharField(max_length=25, blank=True)
    producers_quantity = models.CharField(max_length=25, blank=True)
    line_producers_quantity = models.CharField(max_length=25, blank=True)
    co_producers_quantity = models.CharField(max_length=25, blank=True)
    associate_producers_quantity = models.CharField(max_length=25, blank=True)
    directors_quantity = models.CharField(max_length=25, blank=True)
    unit2_directors_quantity = models.CharField(max_length=25, blank=True)
    executive_producers_rate = models.CharField(max_length=25, blank=True)
    producers_rate = models.CharField(max_length=25, blank=True)
    line_producers_rate = models.CharField(max_length=25, blank=True)
    co_producers_rate = models.CharField(max_length=25, blank=True)
    associate_producers_rate = models.CharField(max_length=25, blank=True)
    directors_rate = models.CharField(max_length=25, blank=True)
    unit2_directors_rate = models.CharField(max_length=25, blank=True)
    executive_producers_total = models.CharField(max_length=25, blank=True)
    producers_total = models.CharField(max_length=25, blank=True)
    line_producers_total = models.CharField(max_length=25, blank=True)
    co_producers_total = models.CharField(max_length=25, blank=True)
    associate_producers_total = models.CharField(max_length=25, blank=True)
    directors_total = models.CharField(max_length=25, blank=True)
    unit2_directors_total = models.CharField(max_length=25, blank=True)
    travel_expenses_producers_dirs = models.CharField(
        max_length=25, blank=True)
    living_expenses_producers_dirs = models.CharField(
        max_length=25, blank=True)
    other_producers_dirs = models.CharField(max_length=25, blank=True)
    fringes_taxes_producers_dirs = models.CharField(max_length=25, blank=True)
    producers_dirs_total = models.CharField(max_length=25, blank=True)
    stars = models.CharField(max_length=25, blank=True)
    stars_rights_payments = models.CharField(max_length=25, blank=True)
    travel_expenses_stars = models.CharField(max_length=25, blank=True)
    living_expenses_stars = models.CharField(max_length=25, blank=True)
    other_stars = models.CharField(max_length=25, blank=True)
    fringes_taxes_stars = models.CharField(max_length=25, blank=True)
    music = models.CharField(max_length=25, blank=True)
    music_supervisor = models.CharField(max_length=25, blank=True)
    travel_expenses_music = models.CharField(max_length=25, blank=True)
    living_expenses_music = models.CharField(max_length=25, blank=True)
    music_rights_addl_songs = models.CharField(max_length=25, blank=True)
    other_music = models.CharField(max_length=25, blank=True)
    fringes_taxes_music = models.CharField(max_length=25, blank=True)
    stars_music_total = models.CharField(max_length=25, blank=True)
    principals_quantity = models.CharField(max_length=25, blank=True)
    principals_units_number = models.CharField(max_length=25, blank=True)
    principals_units_name = models.CharField(max_length=25, blank=True)
    principals_rate = models.CharField(max_length=25, blank=True)
    actors_quantity = models.CharField(max_length=25, blank=True)
    actors_units_number = models.CharField(max_length=25, blank=True)
    actors_units_name = models.CharField(max_length=25, blank=True)
    actors_rate = models.CharField(max_length=25, blank=True)
    stuntcoordinators_quantity = models.CharField(max_length=25, blank=True)
    stuntcoordinators_units_number = models.CharField(
        max_length=25, blank=True)
    stuntcoordinators_units_name = models.CharField(max_length=25, blank=True)
    stuntcoordinators_rate = models.CharField(max_length=25, blank=True)
    stuntperformers_quantity = models.CharField(max_length=25, blank=True)
    stuntperformers_units_number = models.CharField(max_length=25, blank=True)
    stuntperformers_units_name = models.CharField(max_length=25, blank=True)
    stuntperformers_rate = models.CharField(max_length=25, blank=True)
    otherperformers_quantity = models.CharField(max_length=25, blank=True)
    otherperformers_units_number = models.CharField(max_length=25, blank=True)
    otherperformers_units_name = models.CharField(max_length=25, blank=True)
    otherperformers_rate = models.CharField(max_length=25, blank=True)
    extras_quantity = models.CharField(max_length=25, blank=True)
    extras_units_number = models.CharField(max_length=25, blank=True)
    extras_units_name = models.CharField(max_length=25, blank=True)
    extras_rate = models.CharField(max_length=25, blank=True)
    principals_total = models.CharField(max_length=25, blank=True)
    actors_total = models.CharField(max_length=25, blank=True)
    stuntcoordinators_total = models.CharField(max_length=25, blank=True)
    stuntperformers_total = models.CharField(max_length=25, blank=True)
    otherperformers_total = models.CharField(max_length=25, blank=True)
    extras_total = models.CharField(max_length=25, blank=True)
    casting_director = models.CharField(max_length=25, blank=True)
    extras_casting = models.CharField(max_length=25, blank=True)
    other_cast = models.CharField(max_length=25, blank=True)
    fringes_taxes_cast = models.CharField(max_length=25, blank=True)
    rights_payments_cast = models.CharField(max_length=25, blank=True)
    cast_total = models.CharField(max_length=25, blank=True)
    production_manager_quantity = models.CharField(max_length=25, blank=True)
    production_manager_units_number = models.CharField(
        max_length=25, blank=True)
    production_manager_units_name = models.CharField(max_length=25, blank=True)
    production_manager_rate = models.CharField(max_length=25, blank=True)
    production_supervisor_quantity = models.CharField(
        max_length=25, blank=True)
    production_supervisor_units_number = models.CharField(
        max_length=25, blank=True)
    production_supervisor_units_name = models.CharField(
        max_length=25, blank=True)
    production_supervisor_rate = models.CharField(max_length=25, blank=True)
    production_coordinator_quantity = models.CharField(
        max_length=25, blank=True)
    production_coordinator_units_number = models.CharField(
        max_length=25, blank=True)
    production_coordinator_units_name = models.CharField(
        max_length=25, blank=True)
    production_coordinator_rate = models.CharField(max_length=25, blank=True)
    unit_manager_quantity = models.CharField(max_length=25, blank=True)
    unit_manager_units_number = models.CharField(max_length=25, blank=True)
    unit_manager_units_name = models.CharField(max_length=25, blank=True)
    unit_manager_rate = models.CharField(max_length=25, blank=True)
    location_manager_quantity = models.CharField(max_length=25, blank=True)
    location_manager_units_number = models.CharField(max_length=25, blank=True)
    location_manager_units_name = models.CharField(max_length=25, blank=True)
    location_manager_rate = models.CharField(max_length=25, blank=True)
    location_manager_assistant_quantity = models.CharField(
        max_length=25, blank=True)
    location_manager_assistant_units_number = models.CharField(
        max_length=25, blank=True)
    location_manager_assistant_units_name = models.CharField(
        max_length=25, blank=True)
    location_manager_assistant_rate = models.CharField(
        max_length=25, blank=True)
    production_assistants_quantity = models.CharField(
        max_length=25, blank=True)
    production_assistants_units_number = models.CharField(
        max_length=25, blank=True)
    production_assistants_units_name = models.CharField(
        max_length=25, blank=True)
    production_assistants_rate = models.CharField(max_length=25, blank=True)
    production_secretary_quantity = models.CharField(max_length=25, blank=True)
    production_secretary_units_number = models.CharField(
        max_length=25, blank=True)
    production_secretary_units_name = models.CharField(
        max_length=25, blank=True)
    production_secretary_rate = models.CharField(max_length=25, blank=True)
    production_accountant_quantity = models.CharField(
        max_length=25, blank=True)
    production_accountant_units_number = models.CharField(
        max_length=25, blank=True)
    production_accountant_units_name = models.CharField(
        max_length=25, blank=True)
    production_accountant_rate = models.CharField(max_length=25, blank=True)
    production_accountant_assistant_quantity = models.CharField(
        max_length=25, blank=True)
    production_accountant_assistant_units_number = models.CharField(
        max_length=25, blank=True)
    production_accountant_assistant_units_name = models.CharField(
        max_length=25, blank=True)
    production_accountant_assistant_rate = models.CharField(
        max_length=25, blank=True)
    scriptsupervisor_continuity_quantity = models.CharField(
        max_length=25, blank=True)
    scriptsupervisor_continuity_units_number = models.CharField(
        max_length=25, blank=True)
    scriptsupervisor_continuity_units_name = models.CharField(
        max_length=25, blank=True)
    scriptsupervisor_continuity_rate = models.CharField(
        max_length=25, blank=True)
    payroll_quantity = models.CharField(max_length=25, blank=True)
    payroll_units_number = models.CharField(max_length=25, blank=True)
    payroll_units_name = models.CharField(max_length=25, blank=True)
    payroll_rate = models.CharField(max_length=25, blank=True)
    other_production_quantity = models.CharField(max_length=25, blank=True)
    other_production_units_number = models.CharField(max_length=25, blank=True)
    other_production_units_name = models.CharField(max_length=25, blank=True)
    other_production_rate = models.CharField(max_length=25, blank=True)
    directors_assistant_quantity = models.CharField(max_length=25, blank=True)
    directors_assistant_units_number = models.CharField(
        max_length=25, blank=True)
    directors_assistant_units_name = models.CharField(
        max_length=25, blank=True)
    directors_assistant_rate = models.CharField(max_length=25, blank=True)
    assistant_director_1st_quantity = models.CharField(
        max_length=25, blank=True)
    assistant_director_1st_units_number = models.CharField(
        max_length=25, blank=True)
    assistant_director_1st_units_name = models.CharField(
        max_length=25, blank=True)
    assistant_director_1st_rate = models.CharField(max_length=25, blank=True)
    assistant_director_2nd_quantity = models.CharField(
        max_length=25, blank=True)
    assistant_director_2nd_units_number = models.CharField(
        max_length=25, blank=True)
    assistant_director_2nd_units_name = models.CharField(
        max_length=25, blank=True)
    assistant_director_2nd_rate = models.CharField(max_length=25, blank=True)
    assistant_director_3rd_quantity = models.CharField(
        max_length=25, blank=True)
    assistant_director_3rd_units_number = models.CharField(
        max_length=25, blank=True)
    assistant_director_3rd_units_name = models.CharField(
        max_length=25, blank=True)
    assistant_director_3rd_rate = models.CharField(max_length=25, blank=True)
    craft_services_quantity = models.CharField(max_length=25, blank=True)
    craft_services_units_number = models.CharField(max_length=25, blank=True)
    craft_services_units_name = models.CharField(max_length=25, blank=True)
    craft_services_rate = models.CharField(max_length=25, blank=True)
    productionmanager_total = models.CharField(max_length=25, blank=True)
    productionsupervisor_total = models.CharField(max_length=25, blank=True)
    productioncoordinator_total = models.CharField(max_length=25, blank=True)
    unitmanager_total = models.CharField(max_length=25, blank=True)
    locationmanager_total = models.CharField(max_length=25, blank=True)
    locationmanagerassistant_total = models.CharField(
        max_length=25, blank=True)
    productionassistants_total = models.CharField(max_length=25, blank=True)
    productionsecretary_total = models.CharField(max_length=25, blank=True)
    productionaccountant_total = models.CharField(max_length=25, blank=True)
    productionaccountantassistant_total = models.CharField(
        max_length=25, blank=True)
    scriptsupervisorcontinuity_total = models.CharField(
        max_length=25, blank=True)
    payroll_total = models.CharField(max_length=25, blank=True)
    otherproduction_total = models.CharField(max_length=25, blank=True)
    directorsassistant_total = models.CharField(max_length=25, blank=True)
    assistantdirector1st_total = models.CharField(max_length=25, blank=True)
    assistantdirector2nd_total = models.CharField(max_length=25, blank=True)
    assistantdirector3rd_total = models.CharField(max_length=25, blank=True)
    craftservices_total = models.CharField(max_length=25, blank=True)
    productionstaff_total = models.CharField(max_length=25, blank=True)
    production_designer_quantity = models.CharField(max_length=25, blank=True)
    production_designer_units_number = models.CharField(
        max_length=25, blank=True)
    production_designer_units_name = models.CharField(
        max_length=25, blank=True)
    production_designer_rate = models.CharField(max_length=25, blank=True)
    art_director_quantity = models.CharField(max_length=25, blank=True)
    art_director_units_number = models.CharField(max_length=25, blank=True)
    art_director_units_name = models.CharField(max_length=25, blank=True)
    art_director_rate = models.CharField(max_length=25, blank=True)
    art_assistants_quantity = models.CharField(max_length=25, blank=True)
    art_assistants_units_number = models.CharField(max_length=25, blank=True)
    art_assistants_units_name = models.CharField(max_length=25, blank=True)
    art_assistants_rate = models.CharField(max_length=25, blank=True)
    production_assistants_trainees_quantity = models.CharField(
        max_length=25, blank=True)
    production_assistants_trainees_units_number = models.CharField(
        max_length=25, blank=True)
    production_assistants_trainees_units_name = models.CharField(
        max_length=25, blank=True)
    production_assistants_trainees_rate = models.CharField(
        max_length=25, blank=True)
    graphic_artists_quantity = models.CharField(max_length=25, blank=True)
    graphic_artists_units_number = models.CharField(max_length=25, blank=True)
    graphic_artists_units_name = models.CharField(max_length=25, blank=True)
    graphic_artists_rate = models.CharField(max_length=25, blank=True)
    productiondesigner_total = models.CharField(max_length=25, blank=True)
    artdirector_total = models.CharField(max_length=25, blank=True)
    artassistants_total = models.CharField(max_length=25, blank=True)
    productionassistantstrainees_total = models.CharField(
        max_length=25, blank=True)
    graphicartists_total = models.CharField(max_length=25, blank=True)
    other_design = models.CharField(max_length=25, blank=True)
    designlabour_total = models.CharField(max_length=25, blank=True)
    constructioncoordinator_quantity = models.CharField(
        max_length=25, blank=True)
    constructioncoordinator_units_number = models.CharField(
        max_length=25, blank=True)
    constructioncoordinator_units_name = models.CharField(
        max_length=25, blank=True)
    constructioncoordinator_rate = models.CharField(max_length=25, blank=True)
    headcarpenter_quantity = models.CharField(max_length=25, blank=True)
    headcarpenter_units_number = models.CharField(max_length=25, blank=True)
    headcarpenter_units_name = models.CharField(max_length=25, blank=True)
    headcarpenter_rate = models.CharField(max_length=25, blank=True)
    carpenters_quantity = models.CharField(max_length=25, blank=True)
    carpenters_units_number = models.CharField(max_length=25, blank=True)
    carpenters_units_name = models.CharField(max_length=25, blank=True)
    carpenters_rate = models.CharField(max_length=25, blank=True)
    scenicpainters_quantity = models.CharField(max_length=25, blank=True)
    scenicpainters_units_number = models.CharField(max_length=25, blank=True)
    scenicpainters_units_name = models.CharField(max_length=25, blank=True)
    scenicpainters_rate = models.CharField(max_length=25, blank=True)
    headpainter_quantity = models.CharField(max_length=25, blank=True)
    headpainter_units_number = models.CharField(max_length=25, blank=True)
    headpainter_units_name = models.CharField(max_length=25, blank=True)
    headpainter_rate = models.CharField(max_length=25, blank=True)
    painters_quantity = models.CharField(max_length=25, blank=True)
    painters_units_number = models.CharField(max_length=25, blank=True)
    painters_units_name = models.CharField(max_length=25, blank=True)
    painters_rate = models.CharField(max_length=25, blank=True)
    labourers_quantity = models.CharField(max_length=25, blank=True)
    labourers_units_number = models.CharField(max_length=25, blank=True)
    labourers_units_name = models.CharField(max_length=25, blank=True)
    labourers_rate = models.CharField(max_length=25, blank=True)
    other_construction = models.CharField(max_length=25, blank=True)
    constructioncoordinator_total = models.CharField(max_length=25, blank=True)
    headcarpenter_total = models.CharField(max_length=25, blank=True)
    carpenters_total = models.CharField(max_length=25, blank=True)
    scenicpainters_total = models.CharField(max_length=25, blank=True)
    headpainter_total = models.CharField(max_length=25, blank=True)
    painters_total = models.CharField(max_length=25, blank=True)
    labourers_total = models.CharField(max_length=25, blank=True)
    constructionlabour_total = models.CharField(max_length=25, blank=True)
    set_decorator_quantity = models.CharField(max_length=25, blank=True)
    set_decorator_units_number = models.CharField(max_length=25, blank=True)
    set_decorator_units_name = models.CharField(max_length=25, blank=True)
    set_decorator_rate = models.CharField(max_length=25, blank=True)
    assist_set_decorator_quantity = models.CharField(max_length=25, blank=True)
    assist_set_decorator_units_number = models.CharField(
        max_length=25, blank=True)
    assist_set_decorator_units_name = models.CharField(
        max_length=25, blank=True)
    assist_set_decorator_rate = models.CharField(max_length=25, blank=True)
    lead_man_quantity = models.CharField(max_length=25, blank=True)
    lead_man_units_number = models.CharField(max_length=25, blank=True)
    lead_man_units_name = models.CharField(max_length=25, blank=True)
    lead_man_rate = models.CharField(max_length=25, blank=True)
    set_dressers_quantity = models.CharField(max_length=25, blank=True)
    set_dressers_units_number = models.CharField(max_length=25, blank=True)
    set_dressers_units_name = models.CharField(max_length=25, blank=True)
    set_dressers_rate = models.CharField(max_length=25, blank=True)
    swing_gang_quantity = models.CharField(max_length=25, blank=True)
    swing_gang_units_number = models.CharField(max_length=25, blank=True)
    swing_gang_units_name = models.CharField(max_length=25, blank=True)
    swing_gang_rate = models.CharField(max_length=25, blank=True)
    set_dressing_buyer_quantity = models.CharField(max_length=25, blank=True)
    set_dressing_buyer_units_number = models.CharField(
        max_length=25, blank=True)
    set_dressing_buyer_units_name = models.CharField(max_length=25, blank=True)
    set_dressing_buyer_rate = models.CharField(max_length=25, blank=True)
    other_set_dressing = models.CharField(max_length=25, blank=True)
    decoratorset_total = models.CharField(max_length=25, blank=True)
    assistdecoratorset_total = models.CharField(max_length=25, blank=True)
    leadman_total = models.CharField(max_length=25, blank=True)
    dressers_total = models.CharField(max_length=25, blank=True)
    swinggang_total = models.CharField(max_length=25, blank=True)
    dressingbuyer_total = models.CharField(max_length=25, blank=True)
    dressinglabour_total = models.CharField(max_length=25, blank=True)
    property_master_quantity = models.CharField(max_length=25, blank=True)
    property_master_units_number = models.CharField(max_length=25, blank=True)
    property_master_units_name = models.CharField(max_length=25, blank=True)
    property_master_rate = models.CharField(max_length=25, blank=True)
    assist_property_master_quantity = models.CharField(
        max_length=25, blank=True)
    assist_property_master_units_number = models.CharField(
        max_length=25, blank=True)
    assist_property_master_units_name = models.CharField(
        max_length=25, blank=True)
    assist_property_master_rate = models.CharField(max_length=25, blank=True)
    on_set_props_person_quantity = models.CharField(max_length=25, blank=True)
    on_set_props_person_units_number = models.CharField(
        max_length=25, blank=True)
    on_set_props_person_units_name = models.CharField(
        max_length=25, blank=True)
    on_set_props_person_rate = models.CharField(max_length=25, blank=True)
    property_buyer_quantity = models.CharField(max_length=25, blank=True)
    property_buyer_units_number = models.CharField(max_length=25, blank=True)
    property_buyer_units_name = models.CharField(max_length=25, blank=True)
    property_buyer_rate = models.CharField(max_length=25, blank=True)
    armorer_quantity = models.CharField(max_length=25, blank=True)
    armorer_units_number = models.CharField(max_length=25, blank=True)
    armorer_units_name = models.CharField(max_length=25, blank=True)
    armorer_rate = models.CharField(max_length=25, blank=True)
    other_property = models.CharField(max_length=25, blank=True)
    propertymaster_total = models.CharField(max_length=25, blank=True)
    assistpropertymaster_total = models.CharField(max_length=25, blank=True)
    onsetpropsperson_total = models.CharField(max_length=25, blank=True)
    propertybuyer_total = models.CharField(max_length=25, blank=True)
    armorer_total = models.CharField(max_length=25, blank=True)
    propertylabour_total = models.CharField(max_length=25, blank=True)
    head_wrangler_quantity = models.CharField(max_length=25, blank=True)
    head_wrangler_units_number = models.CharField(max_length=25, blank=True)
    head_wrangler_units_name = models.CharField(max_length=25, blank=True)
    head_wrangler_rate = models.CharField(max_length=25, blank=True)
    other_wrangling_labour_quantity = models.CharField(
        max_length=25, blank=True)
    other_wrangling_labour_units_number = models.CharField(
        max_length=25, blank=True)
    other_wrangling_labour_units_name = models.CharField(
        max_length=25, blank=True)
    other_wrangling_labour_rate = models.CharField(
        max_length=25, blank=True)
    headwrangler_total = models.CharField(max_length=25, blank=True)
    otherwranglinglabour_total = models.CharField(max_length=25, blank=True)
    wranglerlabour_total = models.CharField(max_length=25, blank=True)
    fx_supervisor_quantity = models.CharField(max_length=25, blank=True)
    fx_supervisor_units_number = models.CharField(max_length=25, blank=True)
    fx_supervisor_units_name = models.CharField(max_length=25, blank=True)
    fx_supervisor_rate = models.CharField(max_length=25, blank=True)
    assist_fx_quantity = models.CharField(max_length=25, blank=True)
    assist_fx_units_number = models.CharField(max_length=25, blank=True)
    assist_fx_units_name = models.CharField(max_length=25, blank=True)
    assist_fx_rate = models.CharField(max_length=25, blank=True)
    other_fx_labour_quantity = models.CharField(max_length=25, blank=True)
    other_fx_labour_units_number = models.CharField(max_length=25, blank=True)
    other_fx_labour_units_name = models.CharField(max_length=25, blank=True)
    other_fx_labour_rate = models.CharField(max_length=25, blank=True)
    fxsupervisor_total = models.CharField(max_length=25, blank=True)
    assistfx_total = models.CharField(max_length=25, blank=True)
    otherfxlabour_total = models.CharField(max_length=25, blank=True)
    fxlabour_total = models.CharField(max_length=25, blank=True)
    costume_designer_quantity = models.CharField(max_length=25, blank=True)
    costume_designer_units_number = models.CharField(max_length=25, blank=True)
    costume_designer_units_name = models.CharField(max_length=25, blank=True)
    costume_designer_rate = models.CharField(max_length=25, blank=True)
    assist_costume_designer_quantity = models.CharField(
        max_length=25, blank=True)
    assist_costume_designer_units_number = models.CharField(
        max_length=25, blank=True)
    assist_costume_designer_units_name = models.CharField(
        max_length=25, blank=True)
    assist_costume_designer_rate = models.CharField(max_length=25, blank=True)
    head_wardrobe_quantity = models.CharField(max_length=25, blank=True)
    head_wardrobe_units_number = models.CharField(max_length=25, blank=True)
    head_wardrobe_units_name = models.CharField(max_length=25, blank=True)
    head_wardrobe_rate = models.CharField(max_length=25, blank=True)
    wardrobe_assist_quantity = models.CharField(max_length=25, blank=True)
    wardrobe_assist_units_number = models.CharField(max_length=25, blank=True)
    wardrobe_assist_units_name = models.CharField(max_length=25, blank=True)
    wardrobe_assist_rate = models.CharField(max_length=25, blank=True)
    truck_costumer_quantity = models.CharField(max_length=25, blank=True)
    truck_costumer_units_number = models.CharField(max_length=25, blank=True)
    truck_costumer_units_name = models.CharField(max_length=25, blank=True)
    truck_costumer_rate = models.CharField(max_length=25, blank=True)
    other_wardrobe_labour_quantity = models.CharField(
        max_length=25, blank=True)
    other_wardrobe_labour_units_number = models.CharField(
        max_length=25, blank=True)
    other_wardrobe_labour_units_name = models.CharField(
        max_length=25, blank=True)
    other_wardrobe_labour_rate = models.CharField(max_length=25, blank=True)
    costumedesigner_total = models.CharField(max_length=25, blank=True)
    assistcosdesigner_total = models.CharField(max_length=25, blank=True)
    headwardrobe_total = models.CharField(max_length=25, blank=True)
    wardrobeassist_total = models.CharField(max_length=25, blank=True)
    truckcostumer_total = models.CharField(max_length=25, blank=True)
    otherwardrobe_total = models.CharField(max_length=25, blank=True)
    wardrobelabour_total = models.CharField(max_length=25, blank=True)
    makeup_dept_head_quantity = models.CharField(max_length=25, blank=True)
    makeup_dept_head_units_number = models.CharField(
        max_length=25, blank=True)
    makeup_dept_head_units_name = models.CharField(max_length=25, blank=True)
    makeup_dept_head_rate = models.CharField(max_length=25, blank=True)
    key_makeup_quantity = models.CharField(max_length=25, blank=True)
    key_makeup_units_number = models.CharField(max_length=25, blank=True)
    key_makeup_units_name = models.CharField(max_length=25, blank=True)
    key_makeup_rate = models.CharField(max_length=25, blank=True)
    makeup_artist_quantity = models.CharField(max_length=25, blank=True)
    makeup_artist_units_number = models.CharField(max_length=25, blank=True)
    makeup_artist_units_name = models.CharField(max_length=25, blank=True)
    makeup_artist_rate = models.CharField(max_length=25, blank=True)
    key_hairstylist_quantity = models.CharField(max_length=25, blank=True)
    key_hairstylist_units_number = models.CharField(max_length=25, blank=True)
    key_hairstylist_units_name = models.CharField(max_length=25, blank=True)
    key_hairstylist_rate = models.CharField(max_length=25, blank=True)
    hairdresser_quantity = models.CharField(max_length=25, blank=True)
    hairdresser_units_number = models.CharField(max_length=25, blank=True)
    hairdresser_units_name = models.CharField(max_length=25, blank=True)
    hairdresser_rate = models.CharField(max_length=25, blank=True)
    hair_makeup_dailies_quantity = models.CharField(max_length=25, blank=True)
    hair_makeup_dailies_units_number = models.CharField(
        max_length=25, blank=True)
    hair_makeup_dailies_units_name = models.CharField(
        max_length=25, blank=True)
    hair_makeup_dailies_rate = models.CharField(max_length=25, blank=True)
    other_makeup_labour_quantity = models.CharField(max_length=25, blank=True)
    other_makeup_labour_units_number = models.CharField(
        max_length=25, blank=True)
    other_makeup_labour_units_name = models.CharField(
        max_length=25, blank=True)
    other_makeup_labour_rate = models.CharField(max_length=25, blank=True)
    sfx_makeup_quantity = models.CharField(max_length=25, blank=True)
    sfx_makeup_units_number = models.CharField(max_length=25, blank=True)
    sfx_makeup_units_name = models.CharField(max_length=25, blank=True)
    sfx_makeup_rate = models.CharField(max_length=25, blank=True)
    headmakeup_total = models.CharField(max_length=25, blank=True)
    keymakeup_total = models.CharField(max_length=25, blank=True)
    makeupartist_total = models.CharField(max_length=25, blank=True)
    keyhairstylist_total = models.CharField(max_length=25, blank=True)
    hairdresser_total = models.CharField(max_length=25, blank=True)
    hairmakeupdailies_total = models.CharField(max_length=25, blank=True)
    othermakeuplabour_total = models.CharField(max_length=25, blank=True)
    sfxmakeup_total = models.CharField(max_length=25, blank=True)
    makeuplabour_total = models.CharField(max_length=25, blank=True)
    dop_qty = models.CharField(max_length=25, blank=True)
    dop_uno = models.CharField(max_length=25, blank=True)
    dop_una = models.CharField(max_length=25, blank=True)
    dop_rt = models.CharField(max_length=25, blank=True)
    camera_op_qty = models.CharField(max_length=25, blank=True)
    camera_op_uno = models.CharField(max_length=25, blank=True)
    camera_op_una = models.CharField(max_length=25, blank=True)
    camera_op_rt = models.CharField(max_length=25, blank=True)
    cam_ac1_qty = models.CharField(max_length=25, blank=True)
    cam_ac1_uno = models.CharField(max_length=25, blank=True)
    cam_ac1_una = models.CharField(max_length=25, blank=True)
    cam_ac1_rt = models.CharField(max_length=25, blank=True)
    cam_ac2_qty = models.CharField(max_length=25, blank=True)
    cam_ac2_uno = models.CharField(max_length=25, blank=True)
    cam_ac2_una = models.CharField(max_length=25, blank=True)
    cam_ac2_rt = models.CharField(max_length=25, blank=True)
    dit_qty = models.CharField(max_length=25, blank=True)
    dit_uno = models.CharField(max_length=25, blank=True)
    dit_una = models.CharField(max_length=25, blank=True)
    dit_rt = models.CharField(max_length=25, blank=True)
    steadicam_qty = models.CharField(max_length=25, blank=True)
    steadicam_uno = models.CharField(max_length=25, blank=True)
    steadicam_una = models.CharField(max_length=25, blank=True)
    steadicam_rt = models.CharField(max_length=25, blank=True)
    cam_pa_qty = models.CharField(max_length=25, blank=True)
    cam_pa_uno = models.CharField(max_length=25, blank=True)
    cam_pa_una = models.CharField(max_length=25, blank=True)
    cam_pa_rt = models.CharField(max_length=25, blank=True)
    drone_pilot_qty = models.CharField(max_length=25, blank=True)
    drone_pilot_uno = models.CharField(max_length=25, blank=True)
    drone_pilot_una = models.CharField(max_length=25, blank=True)
    drone_pilot_rt = models.CharField(max_length=25, blank=True)
    other_cam_qty = models.CharField(max_length=25, blank=True)
    other_cam_uno = models.CharField(max_length=25, blank=True)
    other_cam_una = models.CharField(max_length=25, blank=True)
    other_cam_rt = models.CharField(max_length=25, blank=True)
    stills_qty = models.CharField(max_length=25, blank=True)
    stills_uno = models.CharField(max_length=25, blank=True)
    stills_una = models.CharField(max_length=25, blank=True)
    stills_rt = models.CharField(max_length=25, blank=True)
    stills_total = models.CharField(max_length=25, blank=True)
    dop_total = models.CharField(max_length=25, blank=True)
    cameraop_total = models.CharField(max_length=25, blank=True)
    camac1_total = models.CharField(max_length=25, blank=True)
    camac2_total = models.CharField(max_length=25, blank=True)
    dit_total = models.CharField(max_length=25, blank=True)
    steadicam_total = models.CharField(max_length=25, blank=True)
    campa_total = models.CharField(max_length=25, blank=True)
    dronepilot_total = models.CharField(max_length=25, blank=True)
    othercam_total = models.CharField(max_length=25, blank=True)
    cameralabour_total = models.CharField(max_length=25, blank=True)
    gaffer_qty = models.CharField(max_length=25, blank=True)
    gaffer_uno = models.CharField(max_length=25, blank=True)
    gaffer_una = models.CharField(max_length=25, blank=True)
    gaffer_rt = models.CharField(max_length=25, blank=True)
    best_boy_qty = models.CharField(max_length=25, blank=True)
    best_boy_uno = models.CharField(max_length=25, blank=True)
    best_boy_una = models.CharField(max_length=25, blank=True)
    best_boy_rt = models.CharField(max_length=25, blank=True)
    electrician_qty = models.CharField(max_length=25, blank=True)
    electrician_uno = models.CharField(max_length=25, blank=True)
    electrician_una = models.CharField(max_length=25, blank=True)
    electrician_rt = models.CharField(max_length=25, blank=True)
    dailies_elec_qty = models.CharField(max_length=25, blank=True)
    dailies_elec_uno = models.CharField(max_length=25, blank=True)
    dailies_elec_una = models.CharField(max_length=25, blank=True)
    dailies_elec_rt = models.CharField(max_length=25, blank=True)
    generator_op_qty = models.CharField(max_length=25, blank=True)
    generator_op_uno = models.CharField(max_length=25, blank=True)
    generator_op_una = models.CharField(max_length=25, blank=True)
    generator_op_rt = models.CharField(max_length=25, blank=True)
    other_elec_qty = models.CharField(max_length=25, blank=True)
    other_elec_uno = models.CharField(max_length=25, blank=True)
    other_elec_una = models.CharField(max_length=25, blank=True)
    other_elec_rt = models.CharField(max_length=25, blank=True)
    gaffer_total = models.CharField(max_length=25, blank=True)
    bestboy_total = models.CharField(max_length=25, blank=True)
    electrician_total = models.CharField(max_length=25, blank=True)
    dailieselec_total = models.CharField(max_length=25, blank=True)
    generatorop_total = models.CharField(max_length=25, blank=True)
    otherelectric_total = models.CharField(max_length=25, blank=True)
    electriclabour_total = models.CharField(max_length=25, blank=True)
    key_grip_qty = models.CharField(max_length=25, blank=True)
    key_grip_uno = models.CharField(max_length=25, blank=True)
    key_grip_una = models.CharField(max_length=25, blank=True)
    key_grip_rt = models.CharField(max_length=25, blank=True)
    best_boy_grip_qty = models.CharField(max_length=25, blank=True)
    best_boy_grip_uno = models.CharField(max_length=25, blank=True)
    best_boy_grip_una = models.CharField(max_length=25, blank=True)
    best_boy_grip_rt = models.CharField(max_length=25, blank=True)
    grips_qty = models.CharField(max_length=25, blank=True)
    grips_uno = models.CharField(max_length=25, blank=True)
    grips_una = models.CharField(max_length=25, blank=True)
    grips_rt = models.CharField(max_length=25, blank=True)
    dailies_grip_qty = models.CharField(max_length=25, blank=True)
    dailies_grip_uno = models.CharField(max_length=25, blank=True)
    dailies_grip_una = models.CharField(max_length=25, blank=True)
    dailies_grip_rt = models.CharField(max_length=25, blank=True)
    dolly_crane_grip_qty = models.CharField(max_length=25, blank=True)
    dolly_crane_grip_uno = models.CharField(max_length=25, blank=True)
    dolly_crane_grip_una = models.CharField(max_length=25, blank=True)
    dolly_crane_grip_rt = models.CharField(max_length=25, blank=True)
    swing_grips_qty = models.CharField(max_length=25, blank=True)
    swing_grips_uno = models.CharField(max_length=25, blank=True)
    swing_grips_una = models.CharField(max_length=25, blank=True)
    swing_grips_rt = models.CharField(max_length=25, blank=True)
    other_grip_labour_qty = models.CharField(max_length=25, blank=True)
    other_grip_labour_uno = models.CharField(max_length=25, blank=True)
    other_grip_labour_una = models.CharField(max_length=25, blank=True)
    other_grip_labour_rt = models.CharField(max_length=25, blank=True)
    keygrip_total = models.CharField(max_length=25, blank=True)
    bestboygrip_total = models.CharField(max_length=25, blank=True)
    grips_total = models.CharField(max_length=25, blank=True)
    dailiesgrip_total = models.CharField(max_length=25, blank=True)
    dollycranegrip_total = models.CharField(max_length=25, blank=True)
    swinggrips_total = models.CharField(max_length=25, blank=True)
    othergriplabour_total = models.CharField(max_length=25, blank=True)
    griplabour_total = models.CharField(max_length=25, blank=True)
    sound_mixer_qty = models.CharField(max_length=25, blank=True)
    sound_mixer_uno = models.CharField(max_length=25, blank=True)
    sound_mixer_una = models.CharField(max_length=25, blank=True)
    sound_mixer_rt = models.CharField(max_length=25, blank=True)
    boom_operator_qty = models.CharField(max_length=25, blank=True)
    boom_operator_uno = models.CharField(max_length=25, blank=True)
    boom_operator_una = models.CharField(max_length=25, blank=True)
    boom_operator_rt = models.CharField(max_length=25, blank=True)
    cable_wrangler_qty = models.CharField(max_length=25, blank=True)
    cable_wrangler_uno = models.CharField(max_length=25, blank=True)
    cable_wrangler_una = models.CharField(max_length=25, blank=True)
    cable_wrangler_rt = models.CharField(max_length=25, blank=True)
    other_sound_labour_qty = models.CharField(max_length=25, blank=True)
    other_sound_labour_uno = models.CharField(max_length=25, blank=True)
    other_sound_labour_una = models.CharField(max_length=25, blank=True)
    other_sound_labour_rt = models.CharField(max_length=25, blank=True)
    soundmixer_total = models.CharField(max_length=25, blank=True)
    boomoperator_total = models.CharField(max_length=25, blank=True)
    cablewrangler_total = models.CharField(max_length=25, blank=True)
    othersoundlabour_total = models.CharField(max_length=25, blank=True)
    soundlabour_total = models.CharField(max_length=25, blank=True)
    tp_coordinator_qty = models.CharField(max_length=25, blank=True)
    tp_coordinator_uno = models.CharField(max_length=25, blank=True)
    tp_coordinator_una = models.CharField(max_length=25, blank=True)
    tp_coordinator_rt = models.CharField(max_length=25, blank=True)
    tp_captain_qty = models.CharField(max_length=25, blank=True)
    tp_captain_uno = models.CharField(max_length=25, blank=True)
    tp_captain_una = models.CharField(max_length=25, blank=True)
    tp_captain_rt = models.CharField(max_length=25, blank=True)
    tp_manager_qty = models.CharField(max_length=25, blank=True)
    tp_manager_uno = models.CharField(max_length=25, blank=True)
    tp_manager_una = models.CharField(max_length=25, blank=True)
    tp_manager_rt = models.CharField(max_length=25, blank=True)
    head_driver_qty = models.CharField(max_length=25, blank=True)
    head_driver_uno = models.CharField(max_length=25, blank=True)
    head_driver_una = models.CharField(max_length=25, blank=True)
    head_driver_rt = models.CharField(max_length=25, blank=True)
    drivers_qty = models.CharField(max_length=25, blank=True)
    drivers_uno = models.CharField(max_length=25, blank=True)
    drivers_una = models.CharField(max_length=25, blank=True)
    drivers_rt = models.CharField(max_length=25, blank=True)
    tpcoordinator_total = models.CharField(max_length=25, blank=True)
    tpcaptain_total = models.CharField(max_length=25, blank=True)
    tpmanager_total = models.CharField(max_length=25, blank=True)
    headdriver_total = models.CharField(max_length=25, blank=True)
    drivers_total = models.CharField(max_length=25, blank=True)
    transportlabour_total = models.CharField(max_length=25, blank=True)
    tech_super_qty = models.CharField(max_length=25, blank=True)
    tech_super_uno = models.CharField(max_length=25, blank=True)
    tech_super_una = models.CharField(max_length=25, blank=True)
    tech_super_rt = models.CharField(max_length=25, blank=True)
    tech_direct_qty = models.CharField(max_length=25, blank=True)
    tech_direct_uno = models.CharField(max_length=25, blank=True)
    tech_direct_una = models.CharField(max_length=25, blank=True)
    tech_direct_rt = models.CharField(max_length=25, blank=True)
    floor_man_qty = models.CharField(max_length=25, blank=True)
    floor_man_uno = models.CharField(max_length=25, blank=True)
    floor_man_una = models.CharField(max_length=25, blank=True)
    floor_man_rt = models.CharField(max_length=25, blank=True)
    light_direct_qty = models.CharField(max_length=25, blank=True)
    light_direct_uno = models.CharField(max_length=25, blank=True)
    light_direct_una = models.CharField(max_length=25, blank=True)
    light_direct_rt = models.CharField(max_length=25, blank=True)
    boardman_qty = models.CharField(max_length=25, blank=True)
    boardman_uno = models.CharField(max_length=25, blank=True)
    boardman_una = models.CharField(max_length=25, blank=True)
    boardman_rt = models.CharField(max_length=25, blank=True)
    audio_qty = models.CharField(max_length=25, blank=True)
    audio_uno = models.CharField(max_length=25, blank=True)
    audio_una = models.CharField(max_length=25, blank=True)
    audio_rt = models.CharField(max_length=25, blank=True)
    vtr_operator_qty = models.CharField(max_length=25, blank=True)
    vtr_operator_uno = models.CharField(max_length=25, blank=True)
    vtr_operator_una = models.CharField(max_length=25, blank=True)
    vtr_operator_rt = models.CharField(max_length=25, blank=True)
    stagehands_qty = models.CharField(max_length=25, blank=True)
    stagehands_uno = models.CharField(max_length=25, blank=True)
    stagehands_una = models.CharField(max_length=25, blank=True)
    stagehands_rt = models.CharField(max_length=25, blank=True)
    other_tv_qty = models.CharField(max_length=25, blank=True)
    other_tv_uno = models.CharField(max_length=25, blank=True)
    other_tv_una = models.CharField(max_length=25, blank=True)
    other_tv_rt = models.CharField(max_length=25, blank=True)
    techsuper_total = models.CharField(max_length=25, blank=True)
    techdirect_total = models.CharField(max_length=25, blank=True)
    floorman_total = models.CharField(max_length=25, blank=True)
    lightdirect_total = models.CharField(max_length=25, blank=True)
    boardman_total = models.CharField(max_length=25, blank=True)
    audio_total = models.CharField(max_length=25, blank=True)
    vtroperator_total = models.CharField(max_length=25, blank=True)
    stagehands_total = models.CharField(max_length=25, blank=True)
    othertv_total = models.CharField(max_length=25, blank=True)
    tvspecificlabour_total = models.CharField(max_length=25, blank=True)
    fringes_taxes_production = models.CharField(max_length=25, blank=True)
    fringes_taxes_design = models.CharField(max_length=25, blank=True)
    fringes_taxes_construction = models.CharField(max_length=25, blank=True)
    fringes_taxes_dressing = models.CharField(max_length=25, blank=True)
    fringes_taxes_property = models.CharField(max_length=25, blank=True)
    fringes_taxes_wrangling = models.CharField(max_length=25, blank=True)
    fringes_taxes_fx = models.CharField(max_length=25, blank=True)
    fringes_taxes_wardrobe = models.CharField(max_length=25, blank=True)
    fringes_taxes_makeup = models.CharField(max_length=25, blank=True)
    fringes_taxes_camera = models.CharField(max_length=25, blank=True)
    fringes_taxes_electric = models.CharField(max_length=25, blank=True)
    fringes_taxes_grip = models.CharField(max_length=25, blank=True)
    fringes_taxes_sound = models.CharField(max_length=25, blank=True)
    fringes_taxes_transport = models.CharField(max_length=25, blank=True)
    fringes_taxes_tv = models.CharField(max_length=25, blank=True)

    class Meta:
        """ Meta for ordering """
        ordering = ['-created_at']

    def __str__(self):
        return f"{self.title} "
