# Generated by Django 3.2.15 on 2023-07-03 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='project',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
