# Generated by Django 3.2.15 on 2023-07-03 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_alter_budget_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='research',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
