# Generated by Django 3.2.15 on 2023-07-03 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0003_alter_budget_research'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='length_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='budget',
            name='miscellaneous',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='budget',
            name='post',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='budget',
            name='prep',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='budget',
            name='rights_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='budget',
            name='shoot',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='budget',
            name='story_rights',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='budget',
            name='wrap',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
