# Generated by Django 3.2.15 on 2023-07-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0004_auto_20230703_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='above_the_line_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='actors_quantity',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='actors_rate',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='actors_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='actors_units_name',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='actors_units_number',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='admin_scenario_quantity',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='admin_scenario_rate',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='admin_scenario_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='admin_scenario_units_name',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='admin_scenario_units_number',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='approvedby',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='approvedbyco',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='associate_producers_quantity',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='associate_producers_rate',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='associate_producers_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='cast_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='casting_director',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='co_producers_quantity',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='co_producers_rate',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='co_producers_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='consultant_expenses',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='consultants_quantity',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='consultants_rate',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='consultants_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='consultants_units_name',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='consultants_units_number',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='development_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='directors_quantity',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='directors_rate',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='directors_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='editors_scenario_quantity',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='editors_scenario_rate',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='editors_scenario_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='editors_scenario_units_name',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='editors_scenario_units_number',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='executive_producers_quantity',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='executive_producers_rate',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='executive_producers_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='extras_casting',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='extras_quantity',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='extras_rate',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='extras_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='extras_units_name',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='extras_units_number',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='fringes_taxes_cast',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='fringes_taxes_music',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='fringes_taxes_producers_dirs',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='fringes_taxes_stars',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='line_producers_quantity',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='line_producers_rate',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='line_producers_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='living_expenses_development',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='living_expenses_music',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='living_expenses_producers_dirs',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='living_expenses_scenario',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='living_expenses_stars',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='music',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='music_rights_addl_songs',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='music_supervisor',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='office_expenses',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='office_expenses_scenario',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='other_cast',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='other_development',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='other_music',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='other_producers_dirs',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='other_scenario',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='other_stars',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='otherperformers_quantity',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='otherperformers_rate',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='otherperformers_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='otherperformers_units_name',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='otherperformers_units_number',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='prelim_budget',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='prelimfin',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='preparedby',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='principals_quantity',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='principals_rate',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='principals_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='principals_units_name',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='principals_units_number',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='producers_dirs_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='producers_quantity',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='producers_rate',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='producers_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='research_development',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='rights_payments_cast',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='scenario_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='staff',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='stars',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='stars_music_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='stars_rights_payments',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='stuntcoordinators_quantity',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='stuntcoordinators_rate',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='stuntcoordinators_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='stuntcoordinators_units_name',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='stuntcoordinators_units_number',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='stuntperformers_quantity',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='stuntperformers_rate',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='stuntperformers_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='stuntperformers_units_name',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='stuntperformers_units_number',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='travel_expenses_development',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='travel_expenses_music',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='travel_expenses_producers_dirs',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='travel_expenses_scenario',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='travel_expenses_stars',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='unit2_directors_quantity',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='unit2_directors_rate',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='unit2_directors_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='writer',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='writers_quantity',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='writers_rate',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='writers_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='writers_units_name',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='writers_units_number',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
