# Generated by Django 3.2.15 on 2023-07-30 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0007_auto_20230727_2252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='production_total',
            new_name='productionstaff_total',
        ),
        migrations.AddField(
            model_name='budget',
            name='below_the_lineB_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='grand_total',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
