# Generated by Django 3.2.15 on 2023-07-30 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0008_auto_20230730_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='fringes_taxes_scenario',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
