# Generated by Django 3.2.15 on 2023-07-31 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0009_budget_fringes_taxes_scenario'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='fringes_taxes_development',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
