# Generated by Django 3.2.15 on 2023-08-31 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0012_auto_20230824_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='audio_qty',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='audio_rt',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='audio_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='audio_una',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='audio_uno',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='boardman_qty',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='boardman_rt',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='boardman_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='boardman_una',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='boardman_uno',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='floor_man_qty',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='floor_man_rt',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='floor_man_una',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='floor_man_uno',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='floorman_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='fringes_taxes_camera',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='fringes_taxes_construction',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='fringes_taxes_design',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='fringes_taxes_dressing',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='fringes_taxes_electric',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='fringes_taxes_fx',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='fringes_taxes_grip',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='fringes_taxes_makeup',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='fringes_taxes_production',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='fringes_taxes_property',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='fringes_taxes_sound',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='fringes_taxes_transport',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='fringes_taxes_tv',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='fringes_taxes_wardrobe',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='fringes_taxes_wrangling',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='light_direct_qty',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='light_direct_rt',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='light_direct_una',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='light_direct_uno',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='lightdirect_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='other_tv_qty',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='other_tv_rt',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='other_tv_una',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='other_tv_uno',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='othertv_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='stagehands_qty',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='stagehands_rt',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='stagehands_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='stagehands_una',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='stagehands_uno',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='tech_direct_qty',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='tech_direct_rt',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='tech_direct_una',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='tech_direct_uno',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='tech_super_qty',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='tech_super_rt',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='tech_super_una',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='tech_super_uno',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='techdirect_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='techsuper_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='tvspecificlabour_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='vtr_operator_qty',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='vtr_operator_rt',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='vtr_operator_una',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='vtr_operator_uno',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='vtroperator_total',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
