# Generated by Django 3.2.15 on 2023-10-20 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0013_auto_20230831_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='above_belowABC_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='above_belowABCandD_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='accomatation_hotels',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='adr',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='adrSup_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='adr_super_qty',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='adr_super_rt',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='adr_super_una',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='adr_super_uno',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='ads',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='aerial_unit',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='animals_purchases',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='animals_rentals',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='animals_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='armaments_permits_fees',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='artSup_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='audio_stock',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='audit',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='backdrops_murals',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='bank_charges',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='basic_package_rent_cam',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='basic_package_rent_elec',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='basic_package_rent_grip',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='basic_package_rent_sound',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='belowB_andC_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='blueprinting',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='boats_planes',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='box_ren_vfx',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='brokerage_insurance',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='buses',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='camera_purchases',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='camera_ship_brok',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='camera_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='carpentry_purchases',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='carpentry_rentals',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='catering',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='closed_caption',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='color_cor',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='colorist_grader_qty',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='colorist_grader_rt',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='colorist_grader_una',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='colorist_grader_uno',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='completion_bond',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='con_script_ccsl',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='construction_other',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='constructionmat_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='contingency',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='corporate_overhead',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='courier_postage',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='craft_expenses',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='crane_rentals',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='crew_2U',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='customs_broker',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='customs_brokerage',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='cyberscanning',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='daily_rentals_cam',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='daily_rentals_elec',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='daily_rentals_grip',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='daily_rentals_sound',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='dalies',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='desSound_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='dig_copies_ver',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='digital_stock',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='distribution_copies',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='drawing_equipment',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='drawing_supplies',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='dress_manufacture',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='dress_purchases',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='dress_rentals',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='dress_repairs_replacements',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='dressing_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='dubs',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='eando',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='ed_sound_ass_qty',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='ed_sound_ass_rt',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='ed_sound_ass_una',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='ed_sound_ass_uno',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='edit_equip',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='edit_equip_nonlin',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='edit_rooms',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='editing_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='editorAss_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='editorMusic_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='editorSound_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='editorVfx_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='editor_ass_qty',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='editor_ass_rt',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='editor_ass_una',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='editor_ass_uno',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='editor_music_qty',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='editor_music_rt',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='editor_music_una',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='editor_music_uno',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='editor_qty',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='editor_rt',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='editor_sound_qty',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='editor_sound_rt',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='editor_sound_una',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='editor_sound_uno',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='editor_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='editor_una',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='editor_uno',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='editor_vfx_qty',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='editor_vfx_rt',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='editor_vfx_una',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='editor_vfx_uno',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='electric_purchases',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='electric_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='epk',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='equipment_2U',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='fares',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='film_stock',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='firnges_pub',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='first_aid',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='fiscal_sponsor_fee',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='folLab_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='foley',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='foley_labour_qty',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='foley_labour_rt',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='foley_labour_una',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='foley_labour_uno',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='food_stabling',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='fringes_taxes_2U',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='fringes_taxes_post',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='fringes_taxes_post_edit',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='fringes_taxes_post_sound',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='fringes_taxes_vfx',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='fuel',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='fx_purchases',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='fx_rentals',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='fx_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='genEx_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='gen_lia',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='generators',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='grader_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='graphics_qty',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='graphics_rt',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='graphics_signs',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='graphics_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='graphics_una',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='graphics_uno',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='green_room',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='grip_purchases',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='grip_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='hair_purchases',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='hair_rentals',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='hard_drives',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='indirCo_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='insur_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='interim_financing',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='interpos_neg',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='legal',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='licences',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='licenses_permits',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='loss_dam_lab',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='loss_damage_cam',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='loss_damage_elec',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='loss_damage_grip',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='lossdam_edit',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='lossdam_sound',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='lossdam_vfx',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='magnetic_transfer',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='makeup_fx',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='makeup_purchases',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='makeup_rentals',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='makeup_ship_brok',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='makeup_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='marine_unit',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='mat_sup_2U',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='meal_penalty',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='medical',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='medical_insurance',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='miniatures_build',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='miniatures_shoot',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='mix',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='motion_capture',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='motorhomes',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='music_edit_equ',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='neg_cutting',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='office_equipment',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='office_other',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='office_rentals',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='office_supplies',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='online',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='opticals',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='otherD_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='other_2U',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='other_animals',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='other_art',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='other_camera',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='other_copies_ver',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='other_dressing',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='other_electric',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='other_fx',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='other_grip',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='other_in',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='other_lab',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='other_makeup',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='other_media_delivery',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='other_post_edit',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='other_post_sound',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='other_post_vfx',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='other_props',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='other_pub',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='other_sound',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='other_transport',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='other_trav_liv',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='other_ward',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='outfitting',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='painting_purchases',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='painting_rentals',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='parking',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='payroll',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='per_diems',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='photography',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='picture_vehicle_ins',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='picture_vehicle_mods',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='picture_vehicle_purchases',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='picture_vehicle_rentals',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='police_control',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='postAccountAss_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='postAccount_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='postAssist_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='postCoordin_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='postLab_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='postSound_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='postStaffFac_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='postSuper_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='postTitles_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='postVersion_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='postVfx_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='post_accountants_ass_qty',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='post_accountants_ass_rt',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='post_accountants_ass_una',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='post_accountants_ass_uno',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='post_accountants_qty',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='post_accountants_rt',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='post_accountants_una',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='post_accountants_uno',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='post_assistants_qty',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='post_assistants_rt',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='post_assistants_una',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='post_assistants_uno',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='post_computers_soft',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='post_consultant',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='post_coordinator_qty',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='post_coordinator_rt',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='post_coordinator_una',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='post_coordinator_uno',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='post_craft',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='post_edit_pur',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='post_it_network',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='post_office_equ',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='post_office_rent',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='post_office_sup',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='post_other',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='post_phone_net',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='post_productionC_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='post_ship',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='post_sound_edit_pur',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='post_store',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='post_supervisor_qty',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='post_supervisor_rt',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='post_supervisor_una',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='post_supervisor_uno',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='power',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='pr',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='pre_mix',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='previews',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='printmaster',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='prints',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='prints_ver',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='proOff_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='pro_package',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='production_cars',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='promotion',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='props_purchases',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='props_rentals',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='props_repairs_replac',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='props_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='pub_press_ex',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='pub_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='rentals_carpentry',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='repairs',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='repairs_construction',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='scaffolding',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='scaffolding_grip',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='secondU_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='shipping',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='site_access',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='site_insurance',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='site_other',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='site_power',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='site_rentals',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='site_security',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='site_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='soundEdAss_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='sound_designer_qty',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='sound_designer_rt',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='sound_designer_una',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='sound_designer_uno',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='sound_edit_equ',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='sound_edit_rooms',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='sound_purchases',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='sound_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='specialty_rent_cam',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='specialty_rent_elec',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='specialty_rent_grip',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='steadicam',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='stills',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='stock',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='stockLab_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='stock_footage',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='stock_prints_processing',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='storage_post',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='studio_fx_equipment',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='studio_other',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='studio_rentals',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='studio_security',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='studio_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='stunts_purchases_rentals',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='subtitles',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='support_vehicles',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='surveying_scouting',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='talent_cars',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='taxis',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='taxis_limos',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='tech',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='telecine',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='tests_other',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='tests_theater_ren',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='titles',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='trailers',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='traliv_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='transfer_stock',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='transfers',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='transfers_deliverables',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='transfers_ver',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='transport',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='transport_2U',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='transport_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='travliv_2U',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='trucks_vans',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='umbrella',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='union_insurance',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='unit_other',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='unit_publicist',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='unit_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='versioning',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='vet',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='vfx_coordinator',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='vfx_ed_system',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='vfx_expenses',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='vfx_post_other_lab',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='vfx_post_vis_team',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='vfx_pre_vis_team',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='vfx_producer',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='vfx_purchases',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='vfx_rentals',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='vfx_storyboard',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='vfx_supervisor',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='vfx_traliv',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='vfx_vendor_1',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='vfx_vendor_10',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='vfx_vendor_2',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='vfx_vendor_3',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='vfx_vendor_4',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='vfx_vendor_5',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='vfx_vendor_6',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='vfx_vendor_7',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='vfx_vendor_8',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='vfx_vendor_9',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='vfx_vendors_x',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='video_stock',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='video_teleprompter',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='walkie_talkies',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='ward_manufact',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='ward_repairs_clean',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='ward_ship_brok',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='wardrobe_purchases',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='wardrobe_rentals',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='wardrobe_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='warehouse_rental',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='website',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='wigs',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='wireless_mics',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
