# Generated by Django 3.2.15 on 2023-10-21 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0014_auto_20231020_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='b_labour_and_costs_total',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='budget',
            name='below_the_lineB_costs_total',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
