# Generated by Django 3.2.15 on 2023-10-22 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0015_auto_20231021_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='phones_net',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
